### ISSUE TITLE
Update JS support to ES6+

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1129] opened 2020-07-06 22:26 UTC
I keep going to use `let` to make a scoped variable (eg in a for loop) but that throws a syntax error. Strangely enough consts are supported (even thought they were added to js in the same version). Support for map functions, amongst other things, would be a great help to writing small, performant code.

**Comment by RobLoach** [comment] 2020-07-07 00:20
It's using DukTape, so we will either want to add ES6 to DukTape, or switch to another JS scripting engine like QuickJS.

**Comment by ChildishGiant** [comment] 2020-07-07 01:15
DukTape seems to have added bits and bobs from ES6 and 7 https://kangax.github.io/compat-table/es6/#duktape2_3. I don't know how involved changing the engine would be but I imagine it's not trivial

**Comment by chronoDave** [comment] 2020-07-08 22:49
I'm not sure if it helps, but it's always possible to use Babel to transpile your ES6+ back to ES5. It'll cost you a few extra tokens, though.

**Comment by RobLoach** [comment] 2020-07-09 02:55
Did something similar with https://github.com/RobLoach/tic80-js .... Found JavaScript performance was a bit slower than Wren/Lua through [some benchmarking](https://github.com/RobLoach/Bunnymark-TIC80) though, so ended up using Wren instead.

**Comment by chronoDave** [comment] 2020-07-09 10:36
Seems I wasn't the only person to write a script for it then :). I wrote [tic-bundle](https://github.com/chronoDave/tic-bundle) which does the same thing. Perhaps I should look into Wren

**Comment by RobLoach** [comment] 2020-08-14 16:55
For bundling Wren, Lua, or Squirel, I put together [scriptpacker](https://github.com/RobLoach/scriptpacker). `tic-bundle` looks awesome for handling JavaScript :smiley_cat:  Nice work!

**Comment by nesbox** [comment] 2020-11-10 13:41
Duplicate of #1191

**Closed by nesbox** 2020-11-10 13:41 UTC
Labels: lang: javascript
