### ISSUE TITLE
Unable to run PNG cartridges using libretro core

### ISSUE THREAD

**Issue by Shatur** [nesbox/TIC-80#2048] opened 2022-12-12 17:38 UTC
When I open a PNG cartridge using RetroArch I have `code is empty` error message. I use the latest release at the time of writing (v1.0.2164, compiled it myself). The same cartridge run perfectly using `tic-80` utility.
Also my RetroArch configuration can run pico-8 cartridges without any problem. But I had to disable built-in RetroArch image viewer for it.

**Comment by bztsrc** [comment] 2022-12-13 03:13
There's a [PR](https://github.com/nesbox/TIC-80/pull/2045) that might fix your issue by providing a reliable way to store cartridge data in PNGs. (I'm just guessing, in lack of sample PNG and detailed error messages I don't know what is causing your problem.)

**Comment by bztsrc** [comment] 2022-12-13 05:50
Ok, I've debugged that. The reason why it isn't working, is because this hasn't been implemented.

The libretro code uses [retro_load_game](https://github.com/nesbox/TIC-80/blob/681f18c0f477e7d7b5b4fea4e330c44028afd34c/src/system/libretro/tic80_libretro.c#L1032) function to load a cartridge.

That function in turn calls [tic80_load](https://github.com/nesbox/TIC-80/blob/aeabb55bef63a11014107d2d0a369ac7ec324530/src/tic.c#L60), which in turn, calls [tic_cart_load](https://github.com/nesbox/TIC-80/blob/323ed1f1e20bb8bd7022c41d46511453487f50bc/src/cart.c#L83), but that last one is only for `.tic` files.

The way how the command line does it, goes like this: when the command is entered, [onLoadCommandConfirmed](https://github.com/nesbox/TIC-80/blob/681f18c0f477e7d7b5b4fea4e330c44028afd34c/src/studio/screens/console.c#L900) checks if the cartridge data was loaded, and calls [tic_cart_load](https://github.com/nesbox/TIC-80/blob/323ed1f1e20bb8bd7022c41d46511453487f50bc/src/cart.c#L83) to parse it. *However* if that's not true, then it checks the file's extension, and calls [loadPngCart](https://github.com/nesbox/TIC-80/blob/7f4ad780d75d2cd8446f856f85ba293af70530eb/src/studio/studio.c#L1446) instead.

As you can see, there's no `loadPngCart` call in `tic80_load`, that function directly calls `tic_cart_load`, so no wonder that PNG cartridges don't work for you.

My guess is, one should add the same `tic_cart_load` / `loadPngCart` logic you see in console.c to `tic80_load` to get PNG cartridges working with libretro core.

Or maybe, as an alternative, PNG check should be added to `tic_cart_load` as I've originally suggested [here](https://github.com/nesbox/TIC-80/issues/2042#issue-1474740328), that would work with all frontends (sokol, sdl etc.), not just libretro (but that code isn't good any more, because the cart data is zlib compressed in the chunk; it's just that's the right place where `loadPngCart` should be called, and not multiplied in start.c, console.c, surf.c etc. IMHO. Alternatively if those sources gets rewritten to use `tic80_load` like all the other frontends, then `tic80_load` would be the ultimate best place for detecting cartridge type).

Cheers,
bzt

**Comment by Shatur** [comment] 2022-12-13 08:22
Thanks for such a detailed breakdown!
I agree with you. Let's see what the maintainers think.

**Comment by bztsrc** [comment] 2022-12-14 01:18
I've added a little change to the PR which will solve your issue, should the PR get merged. Other than that I see no resolution, as linpng isn't linked into libtic80core.a, but that's absolutely needed with the current steganography method.

Cheers,
bzt

**Comment by Shatur** [comment] 2023-01-12 09:59
@bztsrc your PR was merged, can we close this?

**Closed** 2023-01-12 10:02 UTC

**Comment by bztsrc** [comment] 2023-01-13 09:57
> @bztsrc your PR was merged, can we close this?

Unfortunately no, I've just added the fix in the PR's comments, because this issue did not existed when I opened the PR. But now I've added a new PR that actually fixes this.

Cheers,
bzt

**Comment by RobLoach** [comment] 2024-05-23 01:08
Following up on this year-old issue. In addition to the PNG fix, TIC-80 has a number of languages that have had to be disabled in the libretro buildbot TIC-80 core. If you attempt to load a cart that uses one of those languages, it'll report `code is empty`. QuickJS, and MRuby, for instance, are two languages that have had issues compiling across all the platforms on buildbot.
