### ISSUE TITLE
0.80 running quite slower than 0.70.6

### ISSUE THREAD

**Issue by Skaruts** [nesbox/TIC-80#1205] opened 2020-10-03 14:44 UTC
Yesterday I tried 0.80.1344 and I immediately noticed a considerable difference in one of my games: 

0.70.6 (~55fps)
![0 70 6](https://user-images.githubusercontent.com/6277234/94994021-ddd1b300-058c-11eb-82e1-b24f749d17bd.gif)

0.80 (~30fps)
![0 80](https://user-images.githubusercontent.com/6277234/94994078-4456d100-058d-11eb-88ad-b25b5328e723.gif)

I haven't tested this on previous 0.80 versions. Only the latest.

I don't know if this is a TIC-80 problem or a problem on my end. It's possible that this is caused by my ATI Radeon HD 4070 being old and no longer well supported by TIC-80. If this happens to more people, then it's probably not a problem on my end.

I created the small test below. Timing that empty loop in 0.70.6 I get on average ~49.5ms, while on 0.80 it's ~69.5ms.

```lua
local fmt=string.format
local t=0
local total=0
function TIC()
   t=t+1
   cls()

   local t1=time()
   for i=1,5000000 do
      --deliberately empty
   end
   local t2=time()-t1
	
   print(fmt("time    - %.2fms",t2),0,8,15,true)
	
   -- average
   total=total+t2
   print(fmt("average - %.2fms",total/t),0,24,14,true)
end
```

**Comment by nesbox** [comment] 2020-10-06 05:57
Also, we updated LUA to the latest version in the 0.80, maybe this could cause the issue...

**Comment by RobLoach** [comment] 2020-10-09 04:04
Could you share the cart you're testing on? I could give a test on my hardware here.

**Comment by Skaruts** [comment] 2020-10-12 01:01
@RobLoach, 
The small test I made is just a new [cart](https://github.com/nesbox/TIC-80/files/5362445/loop.zip) with that code above. 
The game of life one you can get it on the [tic-80 page](https://tic80.com/play?cart=753) or on [itch](https://skaruts.itch.io/tiny-life).

**Comment by nesbox** [comment] 2020-11-10 14:04
I'll try to analyze it in the profiler.

**Comment by borbware** [comment] 2021-02-02 01:17
I tried to investigate this issue by changing the used Lua version to 5.2. I changed the used Lua branch from .gitmodules to `branch = "v5-2"`. Then, in order to get cmake to build the visual studio solution file at all, i had to remove the `${LUA_DIR}/lutf8lib.c` dependency from CMakeLists.txt. Gulp!

Building the solution in VS2017 still resulted in 11 errors, so I could not test if Lua 5.2 would be faster than 5.3.6.

Anyhow, I'm not even sure if the procedure I tried was anywhere near how it's supposed to be done! Oh well, at least I gave it a shot...

**Comment by borbware** [comment] 2021-04-02 18:50
Hate to break it, but TIC-80 performance has gotten even worse in recent 0.90 builds. In 0.80-1345 (left), my update+draw loop takes around 9ms, but in 0.90-1548 (build 314, right), the same loop takes over 20ms. In terms of framerate, the drop is from 59-60 to 47-50.
 
 This performance drop is quite recent, actually: in 0.90-1545 (build 307), the update loop took about the same time as in 0.80-1345, so it should be easy to pinpoint which commit made it slower. I'll investigate further.
 
![image](https://user-images.githubusercontent.com/19384640/113444244-2b27c380-93fc-11eb-9d7a-429f65b1a32a.png)

**Comment by joshgoebel** [comment] 2021-04-02 19:16
@borbware Can you provide your test case?

**Comment by borbware** [comment] 2021-04-02 19:24
Yeah, sure! Here's the cart in the new fancy png format:
![emuurom](https://user-images.githubusercontent.com/19384640/113446914-8314f900-9401-11eb-8002-338e3c311f0d.png)

To take a look at the main loop performance, press `1`. The topmost entry of the list, `Wupd+Wdrw` records most of the `TIC()` loop. To make the data less chaotic, press `PgUp` or `PgDn` to change the evaluation period from 1 frame to a maximum of 60 frames.

**Comment by joshgoebel** [comment] 2021-04-02 20:12
Do you build the code yourself? You should learn how to use git bisect... git itself can tell you EXACTLY which commit slowed things down (by a very fast process of elimination)... you don't have to "guess". :-)

**Comment by borbware** [comment] 2021-04-02 20:26
I haven't built anything, I'm just comparing different the Github Actions builds (whose build numbers I was referring to earlier). Because 308 was significantly slower than 307, [this](https://github.com/nesbox/TIC-80/commit/ba3abf37437b271f26b7dae7d87e25b6a9b80412) must have been the commit that slowed things down.

**Comment by joshgoebel** [comment] 2021-04-02 20:33
>  this must have been the commit that slowed things down.

Very hard to believe though, that commit only removes code - doesn't add any.  And the code it removes was already extremely lightweight... so at a first glance it looks like a commit that should have 0 impact on anything.

**Comment by borbware** [comment] 2021-04-02 20:40
Hmm, good point. Was there some other changes between builds 307 and 308, then? The size of the sdlgpu windows build jumped from 2943KB to 7447KB, so something must have happened...

**Comment by joshgoebel** [comment] 2021-04-02 22:24
I dunno, git history would know I'd expect... that's why I was recommending bisect vs just testing individual builds... I'm not sure we build every commit that is pushed, do we?

**Comment by borbware** [comment] 2021-04-02 22:32
I'm basing my assumptions on git history: I saw only one new commit between 307 and 308, the one I linked earlier.

**Comment by joshgoebel** [comment] 2021-04-02 23:12
Where are you finding the built assets?  I see the build step in GitHub actions, but I don't know where these files are being uploaded to.

> The size of the sdlgpu windows build jumped from 2943KB to 7447KB, so something must have happened...

That's certainly interesting.  Sounds like perhaps our builds aren't truly reproducible or our dependencies aren't pinned absolutely or something...

**Comment by nesbox** [comment] 2021-04-03 07:27
Hmm, on my side it takes 2.3Mb only
![image](https://user-images.githubusercontent.com/1101448/113471705-de2d0700-9466-11eb-9904-a6950206967f.png)
Something happened with the Github Actions, I'll try to investigate it soon.
Thanks.

**Comment by nesbox** [comment] 2021-04-03 08:05
I compared build logs and seems they updated Visual Studio and the new version builds debug build for an unknown reason.
![image](https://user-images.githubusercontent.com/1101448/113472504-5518ce80-946c-11eb-9033-9c6aad3fd575.png)

**Comment by nesbox** [comment] 2021-04-03 09:13
The problem was with the updated CMake 3.20
Fixed here 16f1463

**Comment by borbware** [comment] 2021-04-03 10:08
Confirmed fixed, performance in 0.90.1554 is now back on par with 0.80.1345. (The performance is still worse than 0.70.6, tho!)

![image](https://user-images.githubusercontent.com/19384640/113475226-e3954c00-947c-11eb-8015-97cb821e7c3d.png)

> Where are you finding the built assets? I see the build step in GitHub actions, but I don't know where these files are being uploaded to.

@joshgoebel On the [build page](https://github.com/nesbox/TIC-80/actions/runs/713952116), scroll down to Artifacts. Those are all downloadable builds. The name "artifacts" is admittedly quite obscure, and you have to be logged in to be able to download them (or even see that those listed artifacts are clickable links).

**Comment by nesbox** [comment] 2021-04-03 11:05
Also, I've done some performance measuring with the code above and got 

![image](https://user-images.githubusercontent.com/1101448/113475964-03c70a00-9481-11eb-92b2-f0275e36065f.png)
on **x86 build**

![image](https://user-images.githubusercontent.com/1101448/113475979-19d4ca80-9481-11eb-8033-63c05a3501ee.png)
on **x64 build**

@borbware could you pls check performance on the latest build 509b418?
because `x64` almost `x1.5` as fast as `x86`

https://github.com/nesbox/TIC-80/actions/runs/714138163

Thanks.

**Comment by borbware** [comment] 2021-04-03 12:45
The new build 0.90.1556 is indeed visibly faster than 1554, I'm glad!

I've made some changes to my game's codebase after migrating from 0.70.6 to 0.80, so can't yet confirm if the performance is on par with 0.70.6. I'll create a new backwards-compatible version for comparison asap.

![image](https://user-images.githubusercontent.com/19384640/113478609-8a381780-9492-11eb-9e07-03c509c0b53a.png)

**Comment by borbware** [comment] 2021-04-03 20:59
Finally modified the cartridge so it runs again on 0.70.6, and the results are in:

![image](https://user-images.githubusercontent.com/19384640/113491140-28e66780-94d7-11eb-9915-5f6ecbc3260b.png)

Not too shabby! The 0.70.6 still beats 0.90.1556, but not by a long shot (at least in this case). Before closing the issue for good, I'd maybe like to see performance parity, but this is very good progress nevertheless, and I'm more than happy with current performance. Thanks @nesbox!

**Comment by borbware** [comment] 2021-04-05 12:21
Btw just noticed that the builds generated with `export win` are still 32-bit, meaning their performance is a bit poorer.

**Comment by nesbox** [comment] 2021-04-06 08:51
Just updated the export files to the latest version.
I think we can close the issue, thanks all for the help.

**Closed by nesbox** 2021-04-06 08:51 UTC

**Comment by Skaruts** [comment] 2022-03-25 07:07
Just tried 0.90, and I also noticed it's still quite a bit slower than 0.70. When I stress test Tiny Life in 0.70 I still get ~60 fps, while in 0.90 I get ~40 fps.

(I improved the performance in the meanwhile, that's why it's not at ~55 fps as it was in the OP.)

**Comment by nesbox** [comment] 2022-03-25 07:24
Could you chack the performance of the dev version?
https://nightly.link/nesbox/TIC-80/workflows/build/main

**Comment by Skaruts** [comment] 2022-03-25 08:34
Oh, good news, it's actually slightly faster than 0.70!

I wasn't quite sure which to download, but I downloaded `workflows/build/main/tic80-winxp.zip`, and my `compute_gen` function is actually about a millisecond faster in that one, so it's at 60 fps as well while stressing it.
