### ISSUE TITLE
keyp behaves differently in TIC and OVR (.js)

### ISSUE THREAD

**Issue by Gallmond** [nesbox/TIC-80#1425] opened 2021-04-21 20:30 UTC
`key` and `keyp` work as expected with default values inside the TIC function, but `keyp` behaves differently in OVR where it must be given every argument specifically. 

```javascript

function TIC(){
       cls(13);
	
	if(key(9)){ // works
		print("I key held!",20,20)
	}

	if(keyp(9)){ // works
		print("I pressed!",20,40)
	}

	if(keyp(9,0,1000000)){ // works
		print("keyp(9,0,10000000)",20,80,5)
	}

}

function OVR() {

	if(key(9)){ // works
		print("I key held!",100,20,5)
	}

	if(keyp(9)){ // does nothing
		print("keyp(9",100,40,5)
	}

	if(keyp(9,0,1000000)){ // works
		print("keyp(9,0,10000000)",100,80,5)
	}

}
```

**Comment by joshgoebel** [comment] 2021-04-21 20:53
I imagine what might be happening here is some "post-tic" stuff is happening after TIC and before OVR.

I wouldn't expect a behavioral difference but I would also say that someone should NOT be doing input inside `OVR`.

**Comment by joshgoebel** [comment] 2021-11-04 11:56
Could we perhaps just add a note on the wiki that the input functions aren't intended for usage inside `OVR` to close this one? Or is this a legit bug we need to fix?

**Comment by joshgoebel** [comment] 2021-11-05 04:43
@Gallmond **Confirmed.**  This is because OVR is called "outside" of a "tick" technically and all the keyboard handling happens "inside" the tick... so when you're calling `btnp` inside OVR you're actually getting the NEXT frames keyboard state (and you're kind of "outside" of the tick entirely) - which is going to lead to inconsistencies like hits.

OVR (and SCN, and BDR) are technically handling during `core_blit` which happens after the current tick end but before the next tick begins.

```
// tic.c
    tic_core_tick_start(tic80->memory);
    tic_core_tick(tic80->memory, &tic80->tickData);
    tic_core_tick_end(tic80->memory);

    tic_core_blit(tic80->memory);
```

@nesbox Does this need to work or can we just declare this say "don't poll input in OVR" and be done with it?

**Comment by joshgoebel** [comment] 2021-11-05 04:47
`tick_end` only deals with: keyboard state, gamepad state, and sound... so I wonder if it could be simply moved after `core_blit`, but technically I think that would be a behavior change - so I'm not sure how nesbox would feel about that since *techncially* that would also be a breaking change (even if it's fixing a bug)...

Making me think the safer answer if "you're doing it wrong" and add a note to the wiki along those lines. :)

**Comment by nesbox** [comment] 2021-11-05 11:29
The `OVR()` was designed to only draw things, but we are trying to rethink it and input will work same everywhere soon, if we are lucky :)

**Comment by joshgoebel** [comment] 2021-11-05 12:11
Yeah, it didn't look super-hard to just put it back inside the tick "scope"... so adding bug label then if we plan to fix this (and I think fixing it would avoid questions in the future). :-)

**Comment by joshgoebel** [comment] 2022-01-07 17:17
@nesbox I think perhaps your recent OVR changes may have solved this one?

**Comment by nesbox** [comment] 2022-01-08 09:25
yes, it's fixed

**Closed by nesbox** 2022-01-08 09:25 UTC
Labels: bug, API, input: keyboard, input: gamepad
