### ISSUE TITLE
export native exporting TIC-80 itself

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#1042] opened 2020-04-07 17:36 UTC
When using command ``export native`` TIC-80 also exporting itself. It is possible, to close the cart in exported file and edit the code, sprites or create new cart.

**Comment by MineRobber9000** [comment] 2020-04-23 01:27
This is not a bug, this is an intended feature.

**Comment by BuoYancYdabl** [comment] 2020-06-24 09:19
> This is not a bug, this is an intended feature.

This "feature" exports the PRO version as well, so users wont buy or build it by themselfs.

**Comment by nesbox** [comment] 2020-11-10 13:27
Duplicate of #169

**Closed by nesbox** 2020-11-10 13:27 UTC
