### ISSUE TITLE
Mouse in Mobile Mode not Working Properly

### ISSUE THREAD

**Issue by Dimsword35** [nesbox/TIC-80#2269] opened 2023-08-19 22:29 UTC
Mouse doesn't seem to be properly working in Tic80 for Android. This is my first time opening an issue so forgive any mistakes.

At first, this issue only happened when running a tic file, but it has now extended to the sprite editor.

When I press the screen, at first, it acts normal, but if I release and press again in another place, a line is drawn between the new spot and the spot touched before it.

_I thought that a line tool would be a useful addition but... that's definitely not it._

This happened after updating, i discovered this after noticing that the config.tic file was reset, and trying to change the font.

**Comment by sogaiu** [comment] 2023-08-20 08:24
Interesting, I connected a pointing device as a work-around for [this](https://github.com/nesbox/TIC-80/issues/2270).  May be that approach isn't going to work too well...in my limited testing it seemed ok here.

FWIW, I was trying to avoid:

> a line is drawn between the new spot and the spot touched before it.

as something similar to that was happening when using a finger or a stylus.

**Comment by nesbox** [comment] 2023-08-24 13:46
looks like a duplicate of #2270

**Closed by nesbox** 2023-08-24 13:46 UTC
