### ISSUE TITLE
Bluetooth keyboard no longer working in Android 0.80 build

### ISSUE THREAD

**Issue by Salwan** [nesbox/TIC-80#1266] opened 2020-12-09 04:19 UTC
This is for Android build.

Tested this in 0.80.1344, same keyboard and devices work fine in 0.70.

Keyboard: Logitech K480

Tested devices:

* NVIDIA Shield TV
* One Plus 7 Pro

Behavior is odd, characters typing doesn't work at all but control keys and shortcuts do.

Inputs that work fine:

* Cursor keys
* Enter, Backspace, Delete, and Escape
* Function keys
* All Ctrl and Alt shotcuts

Inputs that dont work:

* Space
* All characters 

So it seems that input for all printable characters is being ignored or not handled?

**Comment by nesbox** [comment] 2020-12-09 08:47
Seems your keyboard doesn't have input focus, you have to click on the keyboard icon to enable.
![image](https://user-images.githubusercontent.com/1101448/101606337-55501280-3a14-11eb-8d67-3a174882e5a3.png)

**Comment by Salwan** [comment] 2020-12-09 09:18
> Seems your keyboard doesn't have input focus, you have to click on the keyboard icon to enable.

I've just tried this on 0.80 and it did resolve the issue on my phone however the keyboard focus button only shows up when app is in portrait mode.

The Shield TV on the other hand is always in landscape mode so there doesn't seem to be a way to get the keyboard focus button on screen.

I guess this makes it an Android TV specific issue then.

**Comment by nesbox** [comment] 2020-12-09 10:45
Yes, it's an issue with landscape mode then.

**Comment by nesbox** [comment] 2020-12-09 10:46
duplicate of #660

**Closed by nesbox** 2020-12-09 10:46 UTC
