### ISSUE TITLE
Bug: Crash when stop recording with long gif length

### ISSUE THREAD

**Issue by Tau5** [nesbox/TIC-80#543] opened 2018-02-22 22:01 UTC
Steps to reproduce:
1. Increase gif length in TIC config to 120 seconds
2. Record a gif 
3. Stop it (Its not necessary that the gif is 2min. long)
4. Enjoy.

**Comment by frenetic** [comment] 2018-10-09 20:03
Is this still happening on the latest version?
@Tau5 Could you please try to reproduce it?

**Comment by nesbox** [comment] 2020-10-29 09:38
Can't reproduce, maybe will be fixed with #522

**Closed by nesbox** 2020-10-29 09:38 UTC
