### ISSUE TITLE
0.80 fails to load on win7

### ISSUE THREAD

**Issue by another-m00** [nesbox/TIC-80#1181] opened 2020-09-17 14:04 UTC
0.80 (latest build on the offical page) fails to initialise while throwing the following error:
![image](https://user-images.githubusercontent.com/71275068/93480359-a52fa980-f8fd-11ea-9b3d-cf88135b2d50.png)
(translates to:`The procedure's entry point (GetSystemTimePreciseAsFileTime) could not be found in the DLL (Kernel.dll).` )

The app does not show a window at all.
Os version: Windows 7 enterprise (build 7601, SP1)

I'll look trough the code, and try to find the cause, bu I'm in experienced so i can't guaratee success :/

**Comment by nesbox** [comment] 2020-09-17 15:24
We just need to change Windows SDK on the build server.
Thank you.

**Comment by nesbox** [comment] 2020-09-19 07:18
Closing as a duplicate of #743

**Closed by nesbox** 2020-09-19 07:18 UTC
