### ISSUE TITLE
save code.js command saves Lua file instead of JS one

### ISSUE THREAD

**Issue by ViChyavIn** [nesbox/TIC-80#1152] opened 2020-08-25 08:21 UTC
Reproduction steps: just run `save anything.js` and the file will contain JS code instead of Lua code.

TIC-80 0.80.1281-dev

**Comment by nesbox** [comment] 2020-08-25 08:25
Should be fixed in .80
Thank you.

**Comment by potato25** [comment] 2020-08-25 09:08
for a new js file , type ' new js ' in command prompt
there's also script meta-tag and --script meta-tag should contain js , 
default script meta-tag is lua

**Comment by nesbox** [comment] 2020-08-26 11:35
I can't reproduce the issue. 
TIC80 creates Lua cart by default and if you run `save game.js` you will get `game.js` with Lua code inside.
To create JS cart pls use `new js` command and then `save game.js`.
So, I don't see any problems here, closing...

**Closed by nesbox** 2020-08-26 11:35 UTC
Labels: bug

**Comment by ViChyavIn** [comment] 2020-08-26 14:37
@nesbox I'm terribly sorry! I've just found out that I confused with languages and wrote a misleading sentence.

I meant that when you type `save *.js`, it creates a file with *.js* extension but *Lua* code inside, which is incorrect. Running `save *.lua` creates a Lua file with .lua extension and Lua code inside, so I expected that if I put `js` instead of `lua`, I'll have code written in JS accordingly.

**Comment by ViChyavIn** [comment] 2020-08-26 14:40
Nevertheless, I see that extension shouldn't save a different file because the content is taken from the cart, which script is Lua by default.

**Comment by nesbox** [comment] 2020-08-26 14:52
`save` command just saves a file with a given name not paying attention to the script type in a cart, I think you should care about the script in the cart, not TIC.

**Comment by ViChyavIn** [comment] 2020-08-26 16:04
I got it. Thanks!
