### ISSUE TITLE
Application crash on infinite loop

### ISSUE THREAD

**Issue by ChildishGiant** [nesbox/TIC-80#1579] opened 2021-08-31 01:09 UTC
I feel like you should be able to exit out of the game instead of the whole app crashing.

```lua
function TIC()
  while true do
  end
end
```

**Comment by Weeppiko** [comment] 2021-08-31 03:06
Duplicate of #1409
You can hold ESC to exit the loop, but only in Lua.

**Closed** 2021-08-31 09:54 UTC
