### ISSUE TITLE
Export native game close directly

### ISSUE THREAD

**Issue by LordStephen77** [nesbox/TIC-80#391] opened 2017-11-09 00:19 UTC
It would be nice to close native games without going back to the TIC-80 shell, allowing you to distribute the games according to your needs. Exporting a project means creating a copy of TIC-80 that automatically starts the exported cartridge, if you press ESC back to the shell.

A good idea is to include a new meta comment at the beginning of the project (code) that allows you to decide whether to activate the shell in the sport cartridges or close the cartridge directly by doing quit.

It would also be nice to include a custom splash screen at the start of the cartridge, but I think it's possible. They are being tested.

Sorry but I do not find a project forum, so I did not have a choice and I wrote here. Thank you.

**Comment by nesbox** [comment] 2017-11-09 05:43
I'm going to add it as part of TIC Pro and you'll be able to distribute your game without editors and etc.

As for splash screen, it's already done, try to assign cover to the cartridge and this image will be loaded into the video buffer on the start (don't use `cls()` to see it)

I think it's a duplicate of #169, I'll close it

**Closed by nesbox** 2017-11-09 05:43 UTC

**Comment by LordStephen77** [comment] 2017-11-09 10:31
@nesbox Thank you for your response, you have been very helpful. The TIC-80 is great, it has enormous potential. Thanks for your great job.
