### ISSUE TITLE
segfault on libretro core aarch64

### ISSUE THREAD

**Issue by dhwz** [nesbox/TIC-80#2065] opened 2022-12-29 00:17 UTC
The core crashes when a game is loaded. Happening with latest commit.

@jezze
Since this change the retroarch core is instantly crashing
https://github.com/nesbox/TIC-80/commit/2a700111a0dfaec8d92d3bf715bb1d1170367882#diff-2fb8122f88c730713f251fb6c985b2401f11b9f6053f9fc5f55329c98767a7cdR809

**Comment by jezze** [comment] 2023-01-06 14:44
I assume this is libretro? Yeah I wrote in the commit message that this probably was not a good solution because libretro needs to implement the two callback functions that is currently just set to NULL so I think it was a bit early to merge it but its not too late to fix! What is weird though is that libretro should not have worked before my change either because it also didnt set up those two callbacks and should have crasched just like the player. I can try to see if I can fix it possibly. How do I reproduce this crash? I know very little about retroarch.

**Comment by dhwz** [comment] 2023-01-06 14:45
I think it's already related to this change:
0cd38fd3044fb856be1c9a9db4fc2e1191c696e9

**Comment by jezze** [comment] 2023-01-06 14:47
Yeah if it is that change that introduced the problem then yes that makes total sense to me.

**Comment by jezze** [comment] 2023-01-06 14:50
Ok! Knowing what they did I think I can actually whip up a fix for this. Give me some minutes. Are you able to test it for me @dhwz later? Like I said I am not sure how to reproduce it.

**Comment by jezze** [comment] 2023-01-06 15:02
I created a fix here, I think this should work? https://github.com/nesbox/TIC-80/pull/2072

**Comment by dhwz** [comment] 2023-01-06 15:09
Thx, I'll try it and let you know if it's working.

**Comment by dhwz** [comment] 2023-01-06 15:15
@jezze yeah great that did it! I'll apply that as a patch till it's getting merged. Thank you very much! :)

**Comment by nesbox** [comment] 2023-01-12 09:41
fixed here #2072

**Closed by nesbox** 2023-01-12 09:41 UTC
