### ISSUE TITLE
Too small tic80 on Android

### ISSUE THREAD

**Issue by jkeks** [nesbox/TIC-80#1982] opened 2022-07-15 07:03 UTC
![image](https://user-images.githubusercontent.com/1208124/179169805-9036b62d-ab82-4ea0-b70f-67359435d01b.png)
![image](https://user-images.githubusercontent.com/1208124/179170106-3bb939e6-5046-48ae-9321-5cf1c0c0cfa8.png)

there are too small editor

**Comment by nesbox** [comment] 2022-07-15 12:46
Duplicate of #1906
Will be solved by adding "integer scaling: on|off" item to the game menu.

**Closed by nesbox** 2022-07-15 12:46 UTC
