### ISSUE TITLE
Selecting "NO" when prompted to exit TIC-80 resets cart, with sound bug reported on issue #297

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#330] opened 2017-10-08 18:07 UTC
Happens with 0.46.0

The sound bug occurs whether if it's a local cart or SURF cart.

Repro steps:
1. Make unsaved changes to the cart
2. Run cart
3. Click on close button
4. When prompted to exit with unsaved changes, select "NO".
5. Cart is reset

**Comment by josefnpat** [comment] 2017-10-26 19:55
I cannot repro this in 0.46.0 or 0.47.0. Please supply full repro steps.

**Comment by StinkerB06** [comment] 2017-10-26 22:13
Updated issue description

**Comment by josefnpat** [comment] 2017-10-27 00:50
Can you supply more information about your hardware and operating system? I still cannot repro.
![330](https://user-images.githubusercontent.com/646162/32083240-e4f02c6a-ba86-11e7-8aac-42caede3e044.gif)

**Comment by StinkerB06** [comment] 2017-10-27 01:10
Try it with Bare Bones. I notice the issue.

**Comment by josefnpat** [comment] 2017-10-27 03:54
what is Bare Bones?

**Comment by StinkerB06** [comment] 2017-10-27 03:57
A TIC-80 game. In SURF, go to "tic.computer/play" > "Games" and Bare Bones should be on the list. Try the repro steps on there.

**Comment by josefnpat** [comment] 2017-10-27 15:17
![tic80_wtf2](https://user-images.githubusercontent.com/646162/32111357-e2027516-baff-11e7-988a-213bc1995054.gif)
Still can't repro: 0.47.0 with windows 7 on a NVIDIA GeForce GTX 970

Are you sure you're not accidentally pressing reset cart?

**Comment by josefnpat** [comment] 2017-11-02 16:16
Closing due to inactivity.

**Comment by Effer** [comment] 2017-11-02 17:36
Sorry @josefnpat but I can reproduce part of the issue with last repo 0.0.47
The odd fact is that it happens only using the keyboard (not the mouse) so probably the reason you didn't see happening.

Step to reproduce:
- Run tic
- Hit Esc to enter edit mode
- Edit cart
- Ctrl+R to run
- Alt+F4 to close
- Move Right to "NO" on dialog
- Bug: Sound noise.

**Comment by nesbox** [comment] 2017-11-02 17:39
only sound noise reproduces, same as #355

**Comment by josefnpat** [comment] 2017-11-02 18:10
@Effer do you believe that is what @StinkerB06 was attempting to report? if so, as @nesbox pointed out, this is a dupe of #355

**Comment by Effer** [comment] 2017-11-02 19:27
I'm sure I've reproduce the problem as @StinkerB06 described back on 0.0.46. Now with 0.0.47 only the sound issue remains. Sorry didn't notice #355.
 After all it really seems it can be closed @josefnpat

**Closed by Effer** 2017-11-02 19:27 UTC
