### ISSUE TITLE
Outline does not scroll in the code editor

### ISSUE THREAD

**Issue by KatPurpy** [nesbox/TIC-80#1233] opened 2020-11-08 18:42 UTC
If you have a lot of functions and you want to go further than the outline does not scroll making the cursor go out of the screen

![tic80bug](https://user-images.githubusercontent.com/43522532/98481403-152a2400-220b-11eb-923c-60b1a3480e60.gif)

**Comment by nesbox** [comment] 2020-11-09 09:48
We will add scrolling.
Duplicate of #1195.

**Closed by nesbox** 2020-11-09 09:48 UTC
