### ISSUE TITLE
Linux build instructions only work on Debian

### ISSUE THREAD

**Issue by noxarivis** [nesbox/TIC-80#360] opened 2017-10-28 11:29 UTC
Please add instructions for generic Distros

**Comment by josefnpat** [comment] 2017-10-30 18:25
Are you talking about specific dependencies? Or does `make linux64` not work for you? What distros are you running, and can you perhaps tell us what the equivalent dependencies are?

**Comment by nesbox** [comment] 2017-11-08 15:41
duplicate of #367

**Closed by nesbox** 2017-11-08 15:41 UTC
Labels: linux
