### ISSUE TITLE
'Z' key locks up using Bluetooth keyboard for Android

### ISSUE THREAD

**Issue by Anheurystics** [nesbox/TIC-80#349] opened 2017-10-23 02:19 UTC
title says it all really, after pressing Z once i can't press it anymore, plus the onscreen controls show the A button stuck in its pressed position. restarting the app helps.

I saw this mentioned here before at #4 , but I'm not sure if it was properly fixed

thanks!

**Comment by ozbonus** [comment] 2018-01-21 10:37
I have the same issue and more on a Galaxy Tab A 2016 running Nougat and a generic Bluetooth keyboard.

In addition to the z problem:

* Only arrows work after switching back from another app.

* CTRL+ anything has no effect.

**Comment by nesbox** [comment] 2020-10-28 14:32
hmm, still can't reproduce.
closing for now.

**Closed by nesbox** 2020-10-28 14:32 UTC
Labels: bug, platform: android
