### ISSUE TITLE
Bug: sync to cart isnt working properly

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#2143] opened 2023-02-26 20:05 UTC
This is how to replicate the bug. Leave map space empty, set one tile wherever you want with mset() and then make sync to cart. Save the cart. Then run the cart and quit. Youll see that sprite will appear in map editor. But when you try to quit tic asks if you want to leave all changes unsaved and if you will next time you open .tic file youll see that tile from map disapear. This makes impossible to use sync to cart in web and when exported with option "alone" because in those cases user cant "save" the cart in any way.

**Comment by joshgoebel** [comment] 2023-02-26 20:11
This is a duplicate of #595.

**Closed by joshgoebel** 2023-02-26 20:11 UTC

**Comment by BuoYancYdabl** [comment] 2023-02-26 21:15
correct, sorry!
