### ISSUE TITLE
Ubuntu package

### ISSUE THREAD

**Issue by superseeker13** [nesbox/TIC-80#954] opened 2019-11-03 02:15 UTC
Is their any interest in turning this project into a Ubuntu package?

**Comment by RobLoach** [comment] 2019-11-06 00:03
PPA? Flatpak? Snap?

**Comment by Anrock** [comment] 2019-11-06 19:44
Apparently nobody have time for that (except author of #737), see
AppImage #811
Deb packages #737
Snap #253

**Comment by superseeker13** [comment] 2019-11-07 01:18
Ok, I was considering helping to create and maintain a snap package.

**Comment by Anrock** [comment] 2019-11-07 08:34
Ok, so closing as dupe of #253.

**Closed by Anrock** 2019-11-07 08:34 UTC
Labels: platform: linux
