### ISSUE TITLE
How about adding network capability to TIC80?

### ISSUE THREAD

**Issue by zhangew** [nesbox/TIC-80#1284] opened 2020-12-29 07:21 UTC
MultiPlayer games on mobile phone would be nicer.

My idea is: 
1. Connect(Only in local network)
Possible APIs: 
startserver(), only one server at a time.
findserver(), client will use this api to list all available servers at the time.
stopserver(), the server uses it to exit the service status.
connect(), client will use it to connet to the selected server.
disconnect(), client will use it to disconnect from the connected server.
2. Sync the world
syncgame(), server as the sender, clients as receivers.
copy all TIC80 cart memory to all clients, the effect is all players load the same cart at the same time.
startgame(), all players run the same game at the same time.
endgame(). all players stop the game at the same time.
3. Sync the status
syncstatus(), During the game procedure, all players will use it to broadcast the status. Thus the game program will need to keep a struct that holds all statuses which need to be synced.

A rough idea. Might be possible?

**Comment by RobLoach** [comment] 2020-12-29 15:25
Lots of talk over at https://github.com/nesbox/TIC-80/issues/457

**Comment by zhangew** [comment] 2020-12-31 12:03
Thanks. @RobLoach .

**Comment by nesbox** [comment] 2021-01-01 13:12
As for me, I like the idea to share gamepad input between players (or share a small part of RAM) without a new API addition.
Closing as duplicate of #457
Thanks.

**Closed by nesbox** 2021-01-01 13:12 UTC
