### ISSUE TITLE
tic80 0.5 prerelease crashes with ctrl+s or save

### ISSUE THREAD

**Issue by ambyra** [nesbox/TIC-80#417] opened 2017-11-24 18:44 UTC
https://pastebin.com/4Adr5y1S 
game crashes after pressing command+s or typing "save" in tic80 terminal
game doesn't crash if entering "save gamename.js" in tic80 terminal

steps to reproduce:
in osx terminal type "tic80 gamename.js"
escape into editor
press command+s, or type "save" in tic80 terminal

**Comment by nesbox** [comment] 2017-11-24 19:04
hmm, can't reproduce :(
does it reproduce constantly?

**Comment by nesbox** [comment] 2017-11-24 19:34
maybe the problem is with line endings
do you use MacOS or Unix line endings?
could you pls check

**Comment by ambyra** [comment] 2017-11-24 20:44
Yes, happens 100% of the time. I’ll check the line endings when I get home. I’m on OS X. 

I made the doc with VS Code. I imported into tic80 .5 with 

tic80 game.tic -code game.js

Then I saved in tic80 with 

save game2.js

Then I loaded the created file 

tic80 game2.js

Trying to save with command + s or save command crashes immediately, every time

**Comment by ambyra** [comment] 2017-11-25 00:06
[pixelship2.txt](https://github.com/nesbox/TIC-80/files/1502693/pixelship2.txt)
Whether I set the file to LF or CRLF, TIC80 modifies the file to LF and then crashes.

Up to two new lines are added to the end of the file, past // </TILES>, and the end is converted to LF from whatever it was before.

you can rename the attached file to pixelship2.js

**Comment by ambyra** [comment] 2017-11-25 00:10
Also, the file is saved properly before the program crashes.

**Comment by ambyra** [comment] 2017-11-25 00:16
Even if I copy-paste the js game code into a new tic80 file, even without the <PALETTE> and <TILES> sections, it crashes when I try to save.

**Comment by ambyra** [comment] 2017-11-25 02:34
just tested on windows, works fine. So, osx specific

**Comment by nesbox** [comment] 2017-11-26 18:54
@ambyra I made a fix, could you pls test it?
[tic80.zip](https://github.com/nesbox/TIC-80/files/1504144/tic80.zip)

**Comment by ambyra** [comment] 2017-11-27 13:53
Tested on a friend's mac. Still crashes with command + s

**Comment by nesbox** [comment] 2017-11-27 16:56
I built with some additional debug info, could you pls provide me callstack on crash
[tic80.zip](https://github.com/nesbox/TIC-80/files/1506780/tic80.zip)

**Comment by nesbox** [comment] 2017-11-27 17:48
pls test
[tic80.zip](https://github.com/nesbox/TIC-80/files/1506954/tic80.zip)

**Comment by ambyra** [comment] 2017-11-28 00:48
This version works fine. What was the problem?

**Comment by ambyra** [comment] 2017-11-28 04:38
Yep, this works on both OS X computers, saves correctly, no crashes, proper file name. I’ll consider this closed?

**Comment by nesbox** [comment] 2017-11-28 05:41
The problem was with `strcpy` function, it crashed on MacOSX when `src == dst`
Thanks for testing @ambyra 
Closing

**Closed by nesbox** 2017-11-28 05:41 UTC
Labels: bug
