### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by Danny123B** [nesbox/TIC-80#1736] opened 2021-12-14 11:08 UTC
my game keep crashing every time I use keyp() too much and when I made my own map editor in the game it crash as soon as i pressed A to switch tiles and stuff Also every time i load a cart and load and another it softlocks me too. i love TIC80 stuff so much but please fix it

**Comment by nesbox** [comment] 2021-12-14 11:11
Please provide more info, the version you use, OS, and would be great if you attach the cart to reproduce the crash.
Thanks.

**Comment by Danny123B** [comment] 2021-12-14 11:20
> Please provide more info, the version you use, OS, and would be great if you attach the cart to reproduce the crash. Thanks.

TIC -80 0.90.1723

heres the code actually because i dont know how to attach the cart:

-- title:  Lovely 0.0v
-- author: Daniel
-- desc:  A Game
-- script: lua

MAXX=30
MAXY=17

c={x=-7,y=2}  --cam
p={x=8,y=10}  --player
e={x=20,y=10} --npc
t = 0
ch = 0
function menu()
cls(0)

end
r = 0
function signs()
 if mget(p.x,p.y-1) >= 54  and mget(p.x,p.y) == 125 then
print("Jones Church",0,0,12)
end
 if mget(p.x,p.y-1) == 1  and mget(p.x,p.y) == 125 then
print("Sunset Park",0,0,12)
end
--if mget(p.x,p.y-1) == 128  and mget(p.x,p.y) == 125 then
--print("Jakes house",0,0,12)
--end
end
Tips = {"Go Down and right towards the gate","Welcome to the Lovely Demo","Hope you had fun!!"}
function signsp()
 if Tips[r] == "nil" then
 Tips[r] = ""
 end
if not btn(4) then
 r = math.random(1,10)

end

 if btn(4) and mget(p.x,p.y-1) == 125 then
 if Tips[r] == "nil" then
 Tips[r] = ""
 end

 rect(0,0,200,200,0)
print(Tips[r],0,0,12)
end
--if mget(p.x,p.y-1) == 128  and mget(p.x,p.y) == 125 then
--print("Jakes house",0,0,12)
--end
end
b = 0
function MapEditor()
cls()

 map(p.x-15,p.y-8,MAXX,MAXY)
if btnp(0,8,8) then
p.y =p.y - 1
end
if btnp(1,8,8) then
p.y = p.y + 1
end
if btnp(2,8,8) then
p.x = p.x - 1
end
if btnp(3,8,8) then
p.x = p.x + 1
end 
print(t,0,0,2)

if keyp(6) then
t =t + 1
end
if keyp(7)then

t =t - 1
end
if btnp(4,6,6) then
mset(p.x,p.y,t)
end
signs()
--spr(258,p.x*8,p.y*8)
 spr(t,0,0)
 spr(258,15*8,8*8,0)
 if keyp(2) then
 sync(0,b,true)
 print("save")
 end
  if keyp(3) then
 sync(0,b,false)
  print("load")
 end
  if keyp(4) then
 b= b + 1
 end
  if keyp(5) then
  b= b -1
  end
end
function controls()
 if btnp(0,6,6) and mget(p.x,p.y-1)==1 then
  p.y=p.y-1
  c.y=c.y-1
  ch= 1
 end

 if btnp(1,6,6) and mget(p.x,p.y+1)==1 then
  p.y=p.y+1
  c.y=c.y+1
  ch = 0
 end
 if btnp(2,6,6) and mget(p.x-1,p.y)==1 then
  p.x=p.x-1
  c.x=c.x-1
  ch = 3
 end
 if btnp(3,6,6) and mget(p.x+1,p.y)==1 then
  p.x=p.x+1
  c.x=c.x+1
  ch = 2
 end

end
function ladder()

  if btnp(0,6,6) and mget(p.x,p.y-1)==2 then -- ladder
  p.y=p.y-1
  c.y=c.y-1
 end
  if btnp(0,6,6) and mget(p.x,p.y-1)==18 then -- ladder
  p.y=p.y-1
  c.y=c.y-1
 end
   if btnp(1,6,6) and mget(p.x,p.y+1)==34 then -- ladder
  p.y=p.y+1
  c.y=c.y-1
 end
  --if btnp(1,6,6) and mget(p.x,p.y+1)==2 then -- ladder
  --p.y=p.y+1
  --c.y=c.y+1
 --end
  --if btnp(0,6,6) and mget(p.x,p.y+1)==18 then -- ladder
  --p.y=p.y-1
  --c.y=c.y+1
 --end
end
function bridge()
if btnp(0,6,6) and mget(p.x,p.y-1)==64 then
  p.y=p.y-1
  c.y=c.y-1
 end

 if btnp(1,6,6) and mget(p.x,p.y+1)==64 then
  p.y=p.y+1
  c.y=c.y+1
 end
 if btnp(2,6,6) and mget(p.x-1,p.y)==64 then
  p.x=p.x-1
  c.x=c.x-1
 end
 if btnp(3,6,6) and mget(p.x+1,p.y)==64 then
  p.x=p.x+1
  c.x=c.x+1
 end

end
mm = false
PALETTE_MAP = 0x3FF0
blue = 9
red = 2

function Play()

controls()
ladder()
bridge()
if keyp(2) then
m = 1
end
if keyp(3) then
m = 0
end

 --here we draw the screen graphics
 cls(3)
 map(p.x-15,p.y-8,MAXX,MAXY)
 if not mm then
-- music(0,0,true)
 mm = true
 end

signsp()

 spr(272+ch,15*8,8*8,0)
-- spr(272,(e.x-c.x)*8,(e.y-c.y)*8,0)
-- signsp()
end
hx = 13
hy = 10
function helic()
--202 203 204
--if mget(hx,hy) >= 0 then
mset(e.x,e.y,186)
if mget(p.x,p.y+1) == 186 then
print("ok")
for i= 0,240 do
for j= 0,160 do
if mget(i,j) == 160 then
p.x = i
-- draw the sprite
poke4(PALETTE_MAP * 2 + blue, blue) -- swap them back
--poke(0x03FF0,5)
--poke(0x03FF1,5)
--poke(0x03FF2,5)

p.y = j
end
end
end
end 
if mget(p.x,p.y+1) == 218 then
print("ok")
for i= 0,240 do
for j= 0,160 do
poke4(PALETTE_MAP * 2 + blue, red) -- swap the colors

if mget(i,j) == 161 then
p.x = i
p.y = j
end
end
end
end
sync(0,0,true)
poke(0x03FF8,0)--poke(0x03FF2,1)

 --spr(186,(e.x-c.x)*8,(e.y-c.y)*8,0)
  --spr(187,(e.x+1-c.x)*8,(e.y-c.y)*8,0)
--end
--if mget(hx,hy) >= 1 then
--spr(202,0+hx,0+hy)
--spr(203,8+hx,0+hy)
--spr(204,16+hx,0+hy)
--end
end
ow = 0
function SCN()

end
function OVR()

end
function TIC()
MapEditor()
--Play()
helic()
--clip(p.x*73,p.y*73,p.x,p.y)
end

**Comment by nesbox** [comment] 2021-12-14 11:40
Unfortunately, can't reproduce it with the code you provided, maybe add a full `.tic` cart, Github allows to attach `.zip` files.

**Comment by Danny123B** [comment] 2021-12-16 11:36
> Unfortunately, can't reproduce it with the code you provided, maybe add a full `.tic` cart, Github allows to attach `.zip` files.
[lovely0.2v.zip](https://github.com/nesbox/TIC-80/files/7726931/lovely0.2v.zip)
here

**Comment by nesbox** [comment] 2021-12-16 11:50
Hmm, still not crash on Windows, what system do you use?
The only part with "softlocks" is reproducible, the same problem as here #1738.

**Comment by Danny123B** [comment] 2021-12-16 12:19
no its just if I use the MAPE() function I made and press btnp(4,6,6) to change tiles it will crash all the time.

**Comment by another-m00** [comment] 2021-12-28 17:39
Interesting, I could reproduce it in v0.90 (9c38a80). Sometimes Tic80 hangs sometimes just crashes. The exception code in the event log is 0xc0000005 which is a STATUS_ACCESS_VIOLATION error based on Err_6.4.5.exe (error code lookup tool)
Probably because you're trying to access a sprite with negative ID.

**Comment by another-m00** [comment] 2021-12-28 17:43
Yes, definetly because you're trying to access a negative sprite ID :P 
Try `l=(l-1)&&255` to prevent this from happening.

**Comment by nesbox** [comment] 2021-12-28 18:16
The negative sprite ID already fixed in the PR #1665

**Closed by nesbox** 2021-12-28 18:16 UTC
