### ISSUE TITLE
sound cutoff bug

### ISSUE THREAD

**Issue by jackj106** [nesbox/TIC-80#287] opened 2017-09-06 13:27 UTC
while leaving tic80 open with a closed laptop or (maybye) a slept comouter, opening/waking it will cause tic80s sound to be 5-7 seconds behind what it should be.
i accidentally put this up on the itch.io community.
i think ths must happen due to a hierachy issue as far as what gets proccessor while in sleep mode.

**Comment by nesbox** [comment] 2017-09-15 07:58
yes, reproduced it, will fix

**Comment by AnastasiaDunbar** [comment] 2017-10-11 01:06
I have talked about this too.
![image](https://user-images.githubusercontent.com/11806048/31417630-69f91b40-ae63-11e7-9495-14cf1d0ab12b.png)

**Comment by AnastasiaDunbar** [comment] 2017-10-13 23:30
I think sound delays by time because it happened when I left the computer on.

**Comment by jordanranson** [comment] 2018-06-28 17:00
Hey, so its 2018 and this bug still exists. It happens on my 2017 MacBook Pro, using High Sierra. It happens whenever I put the app into full-screen (or take out of full-screen) or when I close and reopen my laptop lid.

**Comment by StinkerB06** [comment] 2019-08-11 00:02
Yes, very annoying and would really love it fixed.

**Comment by another-m00** [comment] 2021-12-28 20:01
This has been fixed since, can we close it now?

**Closed** 2021-12-29 06:09 UTC
Labels: bug
