### ISSUE TITLE
Small font not working in "player" executable

### ISSUE THREAD

**Issue by msx80** [nesbox/TIC-80#909] opened 2019-08-18 14:31 UTC
So i don't know exactly how is called, but the "player" executable (the one without the studio, that only plays a cart, like sdl-renderer), doesn't seem to print any small font text. Not sure why, since the functionality should be generic inside the engine.

To reproduce just make a cart with

```
cls(0)
print("ciao", 10, 10, 15, true, 1, true)
```

The issue affects libretro-core too (that's how i noticed) since it's based on the same "skeleton". For real life example, my game Doors of Doom doesn't show the info box on the right corner, that is printed in small fonts.

**Comment by RobLoach** [comment] 2019-08-20 00:06
Confirmed. Here's the test....
[font_small.tic.zip](https://github.com/nesbox/TIC-80/files/3518102/font_small.tic.zip)

And here's a screenshot in tic80_libretro....

![Screenshot at 2019-08-19 20-06-03](https://user-images.githubusercontent.com/25086/63307573-d97d0480-c2bc-11e9-8361-082be144a331.png)

It's missing the small text.

**Comment by nesbox** [comment] 2019-08-20 08:57
Most likely the problem is here https://github.com/nesbox/TIC-80/blob/5f498e14bbec07e8d429b9653cc92a136d92863e/src/tic80.c#L79
also, we have to add functionality to load a config cart in these "players"

**Comment by StinkerB06** [comment] 2019-08-20 11:30
How do you export a standalone binary without the editors?

**Comment by msx80** [comment] 2019-08-20 12:06
> Most likely the problem is here
> 
> https://github.com/nesbox/TIC-80/blob/5f498e14bbec07e8d429b9653cc92a136d92863e/src/tic80.c#L79

I traced up to there too, but it's the only place where fonts are defined and it looks like it should work for both setups. Strange :)

> also, we have to add functionality to load a config cart in these "players"

i think it should look up in some default user/system folder but not write his own

**Comment by msx80** [comment] 2019-09-03 12:47
I did some more research on this bug, looks like small fonts are loaded from config.tic "system cartridge" when using the full Studio. They are loaded from the foreground spritesheet in studio.c at updateSystemFont(), which is called via config.c at every startup.

In the "player" version, they're only defined in tic80.c Font array, where evidently only the regular font is specified (i think, not sure what format the array is. But it's 1024 elements, so probably 128 char at 8 byte per char).

If i find the time, i'll try to dump the font after it's been loaded by studio and use that to replace the hardcoded one on tic80.c

**Comment by nesbox** [comment] 2019-09-03 14:19
@msx80 thanks for the investigation, just pushed a fix b3e158c

**Comment by RobLoach** [comment] 2019-09-06 04:58
Confirmed the small font of "GUN" is being rendered in libretro...

![Screenshot at 2019-09-06 00-57-42](https://user-images.githubusercontent.com/25086/64402033-71ab1580-d041-11e9-8a09-8acb604be043.png)

**Comment by nesbox** [comment] 2019-09-06 08:20
@RobLoach thanks, so, we can close the issue...

**Comment by Rottenland** [comment] 2020-11-13 12:15
In my example after 0.80 release small font stopped working at all within my game

[rotton_v0.48.tic.zip](https://github.com/nesbox/TIC-80/files/5536696/rotton_v0.48.tic.zip)

**Comment by RobLoach** [comment] 2020-11-14 16:04
That's a great game! Curious why the small font won't work. Small font looks to be working in the cart posted over at https://github.com/nesbox/TIC-80/issues/909#issuecomment-522800016

![Screenshot at 2020-11-14 11-03-01](https://user-images.githubusercontent.com/25086/99151410-fb546b00-2668-11eb-8da5-751f662f889f.png)

**Comment by Rottenland** [comment] 2020-11-15 02:44
Thanks! I made it to learn TIC-80. It was also my first Lua project. Code is a little messy, but does what I need.

Didn't have much time to investigate further, but some normal text is missing too. Only thing at the moment that came to my mind is, I use the values returned by print function to position some text in the project and maybe after update something changed or created another bug

There is also a chance that it previously worked by pure luck and I'm just dumb 😅

**Comment by nesbox** [comment] 2020-11-15 12:11
The main problem I see you're using `print("test",x,y,-1)` with `-1` for the `color` variable.
Please, use `0-15` for color index instead `-1`.
https://github.com/nesbox/TIC-80/wiki/print
Thank you.

**Closed by nesbox** 2020-11-15 12:11 UTC
Labels: bug
