### ISSUE TITLE
SCREAM OF SOUL

### ISSUE THREAD

**Issue by Avevad** [nesbox/TIC-80#944] opened 2019-10-10 05:22 UTC
Please add at least option to choose between tic-80 keyboard and your own virtual keyboard. Tic-80 keyboard could be useful in some situations but I can't code using it.

**Comment by Masternama-8000** [comment] 2019-10-10 12:44
@Avevad TIC-80 Keyboard inside source code. See I maked TIC-80 Keyboard by @nesbox. This old version is **0.70.1**. So new version is **0.80.0-dev** fixed keyboard button,

**Comment by Masternama-8000** [comment] 2019-10-10 13:02
Oops!, sorry, I make own virtual keyboard design. 

### Step by Step

- **Step 1:** _(TIC-80 Command)_ type `config` and press **enter**
See mesaage appear after loaded cart configuration

- **Step 2:** Press **F2** _(Sprite editor)_
See TIC-80 configuration sprites
![sprite keyboard](https://user-images.githubusercontent.com/54476488/66570580-7e181600-eb8b-11e9-8757-2b9297ae1b5e.gif)

- **Step 3:** Draw a keyboard design
Like this:
![new keyboard sprites](https://user-images.githubusercontent.com/54476488/66570680-b9b2e000-eb8b-11e9-89e6-074bbf5f7ee8.gif)

- **Step 4:** Press **Control+s** to save cartridge.  
Or _(TIC-80 command)_ type `save`
See message appear saved a cart.

- **Step 5:** Close your **TIC-80** application and Open your **TIC-80** application. 

- **Step 6:** Done :)

![Screenshot_2019-10-10-18-21-05](https://user-images.githubusercontent.com/54476488/66570971-4a89bb80-eb8c-11e9-9c43-a43216dc86ef.png)

**Comment by Avevad** [comment] 2019-10-11 03:28
The problem isn't that I can't change the design of keyboard. The problem is that there isn't any keyboard in landscape mode. I used to code in the landscape mode but now I can't. I think it is because of your tic-80 keyboard. So I want to have an option to choose between tic-80 keyboard and my Android keyboard (i. e. Hacker's keyboard from GP).

**Comment by Masternama-8000** [comment] 2019-10-11 14:39
Hmm... Turn your mobile rotate.  **_(Landscape Mode)_** see no TIC-80 Keyboard. _**(Portrait Mode)**_ see with TIC-80 Keyboard. 

Look `tic80.h` file inside in the code.
[tic80.h line 125 (**Keyboard**)](https://github.com/nesbox/TIC-80/blob/9894cbfdb465524a8e28b11d718a35bbf4b244de/include/tic80.h#L125).

file name: `tic80.h`
script: C
[`22b0525`](https://github.com/nesbox/TIC-80/commit/22b052588825bc68726ee595edb613d8222359c1)

**Comment by Masternama-8000** [comment] 2019-10-11 15:06
So **0.80.0** update version. Inside the config file. Scroll down new variables. Go to **line 37**

Like this:

```lua
THEME=
{
	CURSOR=
	{
		ARROW=-1,
		HAND=-1,
		IBEAM=-1,
		PIXEL_PERFECT=true,
	},

	CODE =
	{
		BG     =1,
		STRING =14,
		NUMBER =13,
		KEYWORD=6,
		API    =11,
		COMMENT=7,
		SIGN   =10,
		VAR    =15,
		OTHER  =0,
		SELECT =3,
		CURSOR =6,
		SHADOW =true,
		ALT_FONT=false,
	},

	GAMEPAD=
	{
		TOUCH=
		{
			ALPHA=180,
		},
	},
}

 KEYBOARD=
	{
	 VIRTUALMODE=
		{
		 ENABLEKEYBOARD=true,
			MAPPINGKEYBOARD=true,
			MAPMODESHADOW=true,
			MAPMODEPRESSED=true,
			SWITCHKEYBOARD=true,
		},
		GUI=
		{
			TEXT=3,
			SWITCHBUTTON="SWITCH KEYBOARD",
			SWITCHMODEBUTTON="KEYBOARD",
			SWITCHMODEBUTTON2="GAMEPAD",
			DISABLEKEYBOARDLENGTH=10,
			}
		}
				
	
CHECK_NEW_VERSION=false
NO_SOUND=false
GIF_LENGTH=20 -- in seconds
GIF_SCALE=2

-- show SYNC label 
-- when TIC drops 60Hz frames
SHOW_SYNC=false

CRT_MONITOR=false

UI_SCALE=3

---------------------------
function TIC()
	cls()
	local label="This is system configuration cartridge"
	local size=print(label,0,-6)
	print(label,(240-size)//2,(136-6)//2)
end

CRT_SHADER=[[
varying vec2 texCoord;
uniform sampler2D source;
uniform float trg_x;
uniform float trg_y;
uniform float trg_w;
uniform float trg_h;
uniform float scr_w;
uniform float scr_h;

// Emulated input resolution.
vec2 res=vec2(256.0,144.0);

// Hardness of scanline.
//  -8.0 = soft
// -16.0 = medium
float hardScan=-8.0;

// Hardness of pixels in scanline.
// -2.0 = soft
// -4.0 = hard
float hardPix=-3.0;

// Display warp.
// 0.0 = none
// 1.0/8.0 = extreme
vec2 warp=vec2(1.0/64.0,1.0/48.0); 

// Amount of shadow mask.
float maskDark=0.5;
float maskLight=1.5;

//------------------------------------------------------------------------

// sRGB to Linear.
// Assuing using sRGB typed textures this should not be needed.
float ToLinear1(float c){return(c<=0.04045)?c/12.92:pow((c+0.055)/1.055,2.4);}
vec3 ToLinear(vec3 c){return vec3(ToLinear1(c.r),ToLinear1(c.g),ToLinear1(c.b));}

// Linear to sRGB.
// Assuing using sRGB typed textures this should not be needed.
float ToSrgb1(float c){return(c<0.0031308?c*12.92:1.055*pow(c,0.41666)-0.055);}
vec3 ToSrgb(vec3 c){return vec3(ToSrgb1(c.r),ToSrgb1(c.g),ToSrgb1(c.b));}

// Nearest emulated sample given floating point position and texel offset.
// Also zero's off screen.
vec3 Fetch(vec2 pos,vec2 off){
	pos=(floor(pos*res+off)+vec2(0.5,0.5))/res;
	return ToLinear(1.2 * texture2D(source,pos.xy,-16.0).rgb);}

// Distance in emulated pixels to nearest texel.
vec2 Dist(vec2 pos){pos=pos*res;return -((pos-floor(pos))-vec2(0.5));}
		
// 1D Gaussian.
float Gaus(float pos,float scale){return exp2(scale*pos*pos);}

// 3-tap Gaussian filter along horz line.
vec3 Horz3(vec2 pos,float off){
	vec3 b=Fetch(pos,vec2(-1.0,off));
	vec3 c=Fetch(pos,vec2( 0.0,off));
	vec3 d=Fetch(pos,vec2( 1.0,off));
	float dst=Dist(pos).x;
	// Convert distance to weight.
	float scale=hardPix;
	float wb=Gaus(dst-1.0,scale);
	float wc=Gaus(dst+0.0,scale);
	float wd=Gaus(dst+1.0,scale);
	// Return filtered sample.
	return (b*wb+c*wc+d*wd)/(wb+wc+wd);}

// 5-tap Gaussian filter along horz line.
vec3 Horz5(vec2 pos,float off){
	vec3 a=Fetch(pos,vec2(-2.0,off));
	vec3 b=Fetch(pos,vec2(-1.0,off));
	vec3 c=Fetch(pos,vec2( 0.0,off));
	vec3 d=Fetch(pos,vec2( 1.0,off));
	vec3 e=Fetch(pos,vec2( 2.0,off));
	float dst=Dist(pos).x;
	// Convert distance to weight.
	float scale=hardPix;
	float wa=Gaus(dst-2.0,scale);
	float wb=Gaus(dst-1.0,scale);
	float wc=Gaus(dst+0.0,scale);
	float wd=Gaus(dst+1.0,scale);
	float we=Gaus(dst+2.0,scale);
	// Return filtered sample.
	return (a*wa+b*wb+c*wc+d*wd+e*we)/(wa+wb+wc+wd+we);}

// Return scanline weight.
float Scan(vec2 pos,float off){
	float dst=Dist(pos).y;
	return Gaus(dst+off,hardScan);}

// Allow nearest three lines to effect pixel.
vec3 Tri(vec2 pos){
	vec3 a=Horz3(pos,-1.0);
	vec3 b=Horz5(pos, 0.0);
	vec3 c=Horz3(pos, 1.0);
	float wa=Scan(pos,-1.0);
	float wb=Scan(pos, 0.0);
	float wc=Scan(pos, 1.0);
	return a*wa+b*wb+c*wc;}

// Distortion of scanlines, and end of screen alpha.
vec2 Warp(vec2 pos){
	pos=pos*2.0-1.0;    
	pos*=vec2(1.0+(pos.y*pos.y)*warp.x,1.0+(pos.x*pos.x)*warp.y);
	return pos*0.5+0.5;}

// Shadow mask.
vec3 Mask(vec2 pos){
	pos.x+=pos.y*3.0;
	vec3 mask=vec3(maskDark,maskDark,maskDark);
	pos.x=fract(pos.x/6.0);
	if(pos.x<0.333)mask.r=maskLight;
	else if(pos.x<0.666)mask.g=maskLight;
	else mask.b=maskLight;
	return mask;}    

void main() {
	hardScan=-12.0;
	//maskDark=maskLight;
	vec2 start=gl_FragCoord.xy-vec2(trg_x, trg_y);
	start.y=scr_h-start.y;

	vec2 pos=Warp(start/vec2(trg_w, trg_h));

	gl_FragColor.rgb=Tri(pos)*Mask(gl_FragCoord.xy);
	gl_FragColor = vec4(ToSrgb(gl_FragColor.rgb), 1.0);
}
]]
```

**Comment by Avevad** [comment] 2019-10-11 18:13
So couldn't you just tell me how to enable the keyboard in the landscape mode???

**Comment by Masternama-8000** [comment] 2019-10-12 13:23
oops!, sorry, @Avevad I updated config code. go to **line 43** see new `LANDSCAPEKEYBOARDMODE=false`. 

- **Step 1:** Remove `false`
- **Step 2:** type `true`
- **Step 3:** Press **Ctrl+S** to save cart
- **Step 4:** Restart your **TIC-80** application

After  _**TIC-80 Keyboard**_ is changed rotate screen. Now **landscape mode** see **OPEN KEYBOARD** button. Tap **OPEN KEYBOARD** button to _Easy to open_. it works!

**Comment by Avevad** [comment] 2019-10-12 14:56
I can't see that option near line 43

**Comment by Avevad** [comment] 2019-10-12 14:58
Yeah I understand why do I don't see the option. There are too many beta testers on GP for tic 80.

**Comment by Avevad** [comment] 2019-10-12 15:01
So where do I load the beta version of it??

**Comment by Masternama-8000** [comment] 2019-10-12 15:20
yes

**Comment by Masternama-8000** [comment] 2019-10-12 15:24
Link: [TIC-80 Builds](builds.tic.computer)

**Comment by StinkerB06** [comment] 2019-10-12 19:28
@Masternama-8000 Come on, just don't talk about this stuff. Talking about new imaginary settings in the config instead of helping him out with changing it back to the native Android keyboard, won't put him any further towards happiness.

I totally agree with what's going on here. @nesbox, please add an option in the TIC-80 config to toggle between the TIC-80 virtual keyboard and the native Android keyboard, as users are complaining that the virtual one is uncomfortable to work with.

**Comment by Avevad** [comment] 2019-10-13 11:17
I've loaded the new tic build and there is no option. Mb stop lying and add it?

**Comment by Masternama-8000** [comment] 2019-10-13 13:37
@Avevad https://github.com/nesbox/TIC-80/issues/945

**Comment by nesbox** [comment] 2019-10-13 15:29
@Masternama-8000 please, stop spamming to avoid blocking the user!!!

**Comment by Avevad** [comment] 2019-10-18 06:05
So will there be a solution for my problem?

**Comment by nesbox** [comment] 2019-10-18 07:58
sure, will add an option to the config

**Comment by nesbox** [comment] 2019-10-18 07:58
close as a duplicate of #785

**Closed by nesbox** 2019-10-18 07:58 UTC
