### ISSUE TITLE
The screen is weird on my phone

### ISSUE THREAD

**Issue by Lufims** [nesbox/TIC-80#2029] opened 2022-11-03 12:38 UTC
The screen is tiny
![Screenshot_20221103-093638](https://user-images.githubusercontent.com/73536178/199722137-c1d11fe1-89de-4ee1-9677-cb12ace87ec7.png)
Phone: Samsung Galaxy A03 Core

**Comment by Stepan-Savchuk** [comment] 2022-11-11 07:27
The same issue occurred when I switched to PRO version. I use Nokia 5.4

**Comment by joshgoebel** [comment] 2022-12-04 17:56
Do you have a "before" photo and know exactly which version worked well?

**Comment by Stepan-Savchuk** [comment] 2022-12-04 18:59
I don't have a photo before version 1.0, but with 0.9 screen was at least more usable

**Comment by joshgoebel** [comment] 2022-12-04 19:44
> but with 0.9 screen was at least until keyboard

How is that even possible given the aspect ratio??  Even in your snap above the screen could really only be 40% larger before it hits the sides, leaving a substantial space between keyboard and screen.

**Comment by Stepan-Savchuk** [comment] 2022-12-05 08:13
In 0.9 there was less space between keyboard and screen

**Comment by joshgoebel** [comment] 2022-12-17 15:27
Closing as a duplicate of #2031

**Closed by joshgoebel** 2022-12-17 15:27 UTC
