### ISSUE TITLE
I can't open to :(

### ISSUE THREAD

**Issue by EODROID** [nesbox/TIC-80#1504] opened 2021-07-20 14:56 UTC
https://user-images.githubusercontent.com/87712066/126346331-5df57ec9-f7c3-4cce-8ddd-dfe96e2812d8.mp4

**Comment by EODROID** [comment] 2021-07-20 14:56
This is not looping video

**Comment by EODROID** [comment] 2021-07-20 14:59
My Device:
Android 6.1
Sony xperia z3

**Comment by nesbox** [comment] 2021-07-20 15:02
duplicate of #1499

**Closed by nesbox** 2021-07-20 15:02 UTC
