### ISSUE TITLE
Music "joins" channels together after pressing "Play" while music / frame is still playing

### ISSUE THREAD

**Issue by JasonNumberThirteen** [nesbox/TIC-80#749] opened 2018-09-30 11:21 UTC
It's a small thing, but I noticed that music hasn't been stopped when I pressed "Play" / "Play frame" while music is still playing.

**Comment by nesbox** [comment] 2021-04-29 09:07
Can't reproduce it on the latest version 2449804.
Seems already fixed.
Closing, thanks.

**Closed by nesbox** 2021-04-29 09:07 UTC
