### ISSUE TITLE
Declaring an getter to a pseudo-property (JS)

### ISSUE THREAD

**Issue by Win-terMelon** [nesbox/TIC-80#651] opened 2018-08-02 20:08 UTC
Hi,
I saw in the TIC-80 site the FPS / JS by Al Rado

https://tic.computer/play?cart=201

and I looked some strange things (to me).
Firsty, I saw that the variables' inside the object FPS have all the $ simbol, that from what I learn it's just an identifier. But, in some tests that I did, I saw that  when I remove the $ from the variables' names, in the declaration and when we use them inside the **get value()**, with the exception of the returned one that I will talk next, the number of FPS says that is undefined. But when I remove the $ from the returned variable (this.$value) the game **CRASHES**!!!
I don't know if this is an error but I would like someone to explain me please, especially if it isn't an error.

**Comment by AnastasiaDunbar** [comment] 2018-08-04 09:26
This has nothing to do with TIC-80.
The problem is you have `get value()` and `$value:0` and if you remove the dollar sign `$` they'll both have the same name and `this.value` will act like `this.value()` which would call itself recursively just like in this example:
![image](https://user-images.githubusercontent.com/11806048/43674781-ec357572-97d8-11e8-9b57-31337c8da50e.png)

So you'll have to switch from this:
```js
var FPS = {
  $value:0,
  $frames:0,
  $lastTime:0,
  get value() {
    if (time()-this.$lastTime <= 1000) {
      this.$frames=this.$frames+1
    } else {
      this.$value=this.$frames
      this.$frames=0
      this.$lastTime=time()
    }
    return this.$value
  }
}
```
To this:
```js
var FPS={
	lastFrame:0,
	frames:0,
	lastTime:0,
	get value(){
		if(time()-this.lastTime<=1000){
			this.frames++;
		}else{
			this.lastFrame=this.frames;
			this.frames=0;
			this.lastTime=time();
		}
		return this.lastFrame;
	}
};
```

**Comment by Win-terMelon** [comment] 2018-08-04 10:11
Thank you Anastasia Dunbar for the explanation.
Sorry it this was a silly question, I'm don't have much of programming experience.
Now I understand what was wrong. Thank you one more time!

**Comment by frenetic** [comment] 2018-10-09 20:36
@Win-terMelon Thank you for using TIC80. Im happy you learned something. I hope you are having fun with TIC80.
If this question was solved, could you please consider closing this issue?

**Closed** 2018-10-09 20:51 UTC
