### ISSUE TITLE
Blank horizontal lines while the screen refreshes

### ISSUE THREAD

**Issue by fmaida** [nesbox/TIC-80#300] opened 2017-09-18 13:46 UTC
I'm using TIC-80 0.45.0 dev on macOS 10.12.6

When I open TIC-80 in a window, sometimes when the screen refreshes I can see some blank horizontal lines appearing randomly here and there. This is how they appear on my desktop:

![tic_screen_issue](https://user-images.githubusercontent.com/605017/30544912-5855f56c-9c88-11e7-9133-a74ce49e6d05.gif)

If I instead run TIC-80 in fullscreen, apparently those blank lines appears very rarely.

I'm not sure but I think that I started having this issue since version 0.30

**Comment by nesbox** [comment] 2017-09-18 13:52
Hmm, I've never seen it before, could you reproduce it on earlier versions and find the first appearing
you can find all the versions here https://github.com/nesbox/tic.computer/releases

**Comment by fmaida** [comment] 2017-09-18 14:00
Sure. I just tried different releases of TIC-80 and apparently the first one that has this problem is v0.25.0. 

v0.24.0 runs fine, and starting from v0.25.0 I can see them - even if they're not as many as in v0.45.

**Comment by nesbox** [comment] 2017-09-18 14:04
hmm, thanks, I'll see what I broke :)

**Comment by fmaida** [comment] 2017-09-18 14:05
I also forgot to mention that if I export a cart in HTML5 and open it in Chrome, I don't see any blank lines.

**Comment by frenetic** [comment] 2017-12-11 17:18
Could you please test on version `0.50.1`+?

**Comment by fmaida** [comment] 2017-12-12 08:00
I tried v0.50.1 Pro for a couple of hours in the past two days and so far I'm not actually experiencing any of the problems I had in the past with random blank lines.

**Comment by nesbox** [comment] 2017-12-12 08:03
great
so, we can close the issue
thanks @fmaida

**Closed by nesbox** 2017-12-12 08:03 UTC
Labels: bug

**Comment by fmaida** [comment] 2017-12-12 08:05
Thank you for fixing the issue for me ;-)

**Comment by nesbox** [comment] 2017-12-12 08:07
if I knew what the problem was :)
