### ISSUE TITLE
Code Editor Tabs 

### ISSUE THREAD

**Issue by SavageRage69** [nesbox/TIC-80#1887] opened 2022-04-17 10:05 UTC
It would be cool if tic80 had code tabs like pico8.
![untitled_1_0](https://user-images.githubusercontent.com/83941963/163709592-fd5e77ec-d254-426c-b9da-68b05ac12019.gif)
This would make writing and managing code in the editor a lot easier. You just have one tab that contains all of your code right now, which makes managing larger projects extremely difficult. 
![image](https://user-images.githubusercontent.com/83941963/163709751-632e4e59-f22c-45cb-b27a-0d567b537c50.png)
It would be easier to write clean code and read other people's code if there were code tabs. This is a feature that I would love to see implemented to tic80.

**Comment by spooneystone** [comment] 2022-04-17 10:12
This would be really handy. One file for all the code gets crazy

**Comment by TimotheeGreg** [comment] 2023-08-24 21:00
I think this is a duplicate of #569.

**Closed** 2023-08-25 15:33 UTC
