### ISSUE TITLE
Gamepad input stops working upon resume

### ISSUE THREAD

**Issue by technomancy** [nesbox/TIC-80#1187] opened 2020-09-22 15:42 UTC
When you hit ESC to stop a game and then start it again with `resume` then the `btn` function no longer works; it returns false no matter whether a key is pressed.

Repro steps:

* Launch TIC-80
* Enter `run` for the default cart
* Observe that the arrows move the sprite
* Press ESC
* Enter `resume`
* Press the arrows, observe that the sprite does not move

If you modify the cart to use `key` rather than `btn` then the bug does not happen.

**Comment by RobLoach** [comment] 2020-09-22 15:55
Which platform are you on?

**Comment by RobLoach** [comment] 2020-09-22 15:55
Which platform are you on?

**Comment by technomancy** [comment] 2020-09-22 16:08
Oh right, sorry; this is on Debian Linux under X.

**Comment by nesbox** [comment] 2020-09-28 07:36
Seems duplicate of #1164

**Closed by nesbox** 2020-09-28 07:36 UTC

**Comment by technomancy** [comment] 2020-09-29 15:35
You're right; this is fixed. Thanks!
