### ISSUE TITLE
Ability to assign physical gamepad buttons in keymap

### ISSUE THREAD

**Issue by nalquas** [nesbox/TIC-80#260] opened 2017-08-11 09:33 UTC
Currently, if you want to use a physical gamepad for playing your TIC-80 games, you have to map your gamepad buttons to keyboard keys with an external program (like Steam) only to then map these keyboard keys to TIC-80 with keymap.

It would be much easier to use a physical gamepad if TIC-80 accepted inputs from other devices than the keyboard to be mapped with the keymap command (like joysticks or gamepads).
As a result, the user could, for example, map the A-key to their gamepad's A-button.
![mapcontrollers](https://user-images.githubusercontent.com/22664233/29207970-72df32fe-7e88-11e7-9a86-764b8f1b3760.png)

**Comment by to90zeroblue** [comment] 2017-09-15 12:31
I would be very happy to have this one as well!!!

**Comment by trelemar** [comment] 2017-09-16 19:39
I want my GameSir G4s to work so bad with this on Android, sadly only the dpad works. Hoping this gets implemented.

**Comment by nesbox** [comment] 2020-11-10 13:44
Duplicate of #1154

**Closed by nesbox** 2020-11-10 13:44 UTC
Labels: enhancement, input: gamepad
