### ISSUE TITLE
strange behavior of demo program luamark

### ISSUE THREAD

**Issue by jpph** [nesbox/TIC-80#2008] opened 2022-08-15 19:59 UTC
When running the demo, in bunny folder, luamark.tic, you can see that bunny are created by pack of 5, but with same random x, y and speed!
I can not understand how it is possible since the new method is called 5 times.
you can check it, if you press quickly up arrow, coutngin 25 bunny but only 5 on the screen ...

**Comment by joshgoebel** [comment] 2022-12-04 17:58
I feel like I saw this discussed and resolved in another ticket, am I imagining things?

**Comment by nesbox** [comment] 2023-01-12 22:11
hmm, interesting
should be investigated

**Comment by AlecTroemel** [comment] 2023-01-27 15:29
In `luamark.tic` I changed the `btn` calls to `btnp`, and confirmed it does create the bunnys in groups of 5. However this is actually the intent of the code, https://github.com/nesbox/TIC-80/blob/main/demos/bunny/luamark.lua#L99

```lua
	if btn(0) then
		for i = 1, 5 do
			table.insert(bunnies, Bunny:new())
		end
	end
```

It is odd to me that all 5 of the new bunnys have the same velocity, but different positions. Both those use calls to `math.random`. The one difference is that the position passes parameters to `math.random`, while the velocity call does not

```lua

function randomFloat(lower, greater)
	return (math.random() * (greater - lower)) + lower;
end

Bunny = {width=0,height=0,x=0,y=0,speedX=0,speedY=0,sprite=0}

function Bunny:new(o)
	o = o or {}
	setmetatable(o, self)
	self.__index = self
	self.width = 26
	self.height = 32
	self.x = math.random(0, screenWidth - self.width)
	self.y = math.random(0, screenHeight - self.height)
	self.speedX = randomFloat(-100, 100) / 60
	self.speedY = randomFloat(-100, 100) / 60
	self.sprite = 1
	return o
end
```

**Comment by jpph** [comment] 2023-01-27 16:07
My experience was same initial position and same speed for all 5. A pack of 5 is indeed intended but they should have different initial position and initial speed

**Closed** 2023-01-29 18:51 UTC

**Comment by jpph** [comment] 2023-01-29 19:03
Nobody wants to investigate the strange behavior? I understand you fixed the example program to go around the bug, but the bug shouldn't be there anyway...

**Comment by AlecTroemel** [comment] 2023-01-29 22:32
@jpph I agree my MR was just a work around. Could it possibly be something with the lua version were on `5.3.6`? Just looking at [the commit we're on](https://github.com/lua/lua/tree/75ea9ccbea7c4886f30da147fb67b693b2624c26) it seems to be 2 years old, maybe the OOP style being used was only added in 5.4?

**Comment by AlecTroemel** [comment] 2023-01-29 22:49
Ok did a bit more digging, Im guessing the original implementation used these example as a reference https://www.tutorialspoint.com/lua/lua_object_oriented.htm. (that page showed up towards the top of a google search for lua OOP). However I'm able  recreate our issue I was seeing in pure lua (no tic80 involved) with basically their identical example..

```lua
-- Meta class
Shape = {area = 0}

-- Base class method new

function Shape:new (o,side)
   o = o or {}
   setmetatable(o, self)
   self.__index = self
   side = side or 0
   self.area = side*side;
   return o
end

-- Base class method printArea

function Shape:printArea ()
   print("The area is ",self.area)
end

-- Creating an object
myshape = Shape:new(nil,1)
myshape2 = Shape:new(nil,2)
myshape3 = Shape:new(nil,3)

myshape:printArea()
-- The area is 	9
-- this is wrong! 
```

I've reached out to tutorialpoint about this.. but im still not sure _why_ this doesnt work
