### ISSUE TITLE
Switching between apps turns TIC-80's screen black on Android

### ISSUE THREAD

**Issue by Spreit** [nesbox/TIC-80#657] opened 2018-08-12 08:16 UTC

**Comment by pcornier** [comment] 2018-08-12 16:48
Same thing for me on Oneplus 6. And everything is tinted blue in TIC-80.

**Comment by nesbox** [comment] 2018-08-12 20:51
yes, reproduced on my side

**Comment by Quistnix** [comment] 2018-08-13 11:39
The blue tint can be fixed by turning on "disable HW overlays" in development settings.

**Comment by pcornier** [comment] 2018-08-13 12:48
@Quistnix thank you so much! I confirm, HW overlays turned off fixed the blue tint.

**Comment by pcornier** [comment] 2018-08-23 22:13
I noted that SDLActivity.onNativeSurfaceChanged() generates an error "draw context is NULL" on resume. It looks like the context is lost somewhere.

**Comment by pcornier** [comment] 2019-02-21 08:27
Any progress on the black screen problem? Sorry to add some pressure on this but that's a real blocker for me. I've stopped using TIC-80 for months now.

**Comment by alexamy** [comment] 2019-02-21 21:15
Have black screen when switching apps on android 9, tic-80 0.70.7 pro. 
Really annoying.

**Comment by fadookie** [comment] 2019-03-05 22:27
Cross-posting my observations from #451

> Not sure if this is the same issue I'm having but it appears as if any time TIC-80 is backgrounded, upon resuming it shows a black screen. This makes it very difficult to use as an editor. It does seem that sound continues to play and it responds to the back button.
> 
> Device: Google Pixel 1st Gen
> OS: Android 9.0

I agree that this renders the app more or less unusable on android for the purpose of making carts.

**Comment by oktopuss** [comment] 2019-09-16 07:37
Same problem with an Asus Zenfone Max Pro M1 using android 9

**Comment by RandomErrorMessage** [comment] 2019-10-08 19:31
I was excited about playing with this on my phone, but I'm also affected with my LG G4.

**Comment by nesbox** [comment] 2019-12-11 13:49
fixed with the PR #974

**Closed by nesbox** 2019-12-11 13:49 UTC
Labels: bug

**Comment by pcornier** [comment] 2019-12-17 15:25
@nesbox are you able to publish a new version (pro) with only that fix included and before the new official release? I'd love to see TIC-80 back on my phone! 😅

**Comment by nesbox** [comment] 2019-12-17 16:28
Huh, a bit difficult for me because the current version builds on CI servers when previous I built manually and have to configure my system a lot to do it again.
Please wait for the release, sorry :)

**Comment by pcornier** [comment] 2019-12-17 16:51
No problemo, thanks for your quick answer!

**Comment by StinkerB06** [comment] 2019-12-17 17:25
> @nesbox are you able to publish a new version (pro) with only that fix included and before the new official release? I'd love to see TIC-80 back on my phone!

Have you seen this? :
https://builds.tic.computer/master/2019.12.17/android

**Comment by BraininaBowl** [comment] 2019-12-17 20:21
> > @nesbox are you able to publish a new version (pro) with only that fix included and before the new official release? I'd love to see TIC-80 back on my phone!
> 
> Have you seen this? :
> https://builds.tic.computer/master/2019.12.17/android

That doesn't seem to be the pro version though. Or at least, my additional banks are missing.

**Comment by nesbox** [comment] 2019-12-17 20:28
@BraininaBowl yes, we deploy only non-pro version to the server

**Comment by StinkerB06** [comment] 2019-12-17 21:16
> > > @nesbox are you able to publish a new version (pro) with only that fix included and before the new official release? I'd love to see TIC-80 back on my phone!
> > 
> > 
> > Have you seen this? :
> > https://builds.tic.computer/master/2019.12.17/android
> 
> That doesn't seem to be the pro version though. Or at least, my additional banks are missing.

You'll need to compile TIC-80 PRO yourself. Follow the build instructions on the main `readme.md`, and make sure that the flag for building the PRO version is set.

**Comment by pcornier** [comment] 2019-12-18 16:46
Thank you @StinkerB06 ! I created a Dockerfile to compile the Android version: https://gist.github.com/pcornier/eb7a4c612b0ba176d1b4c14bd12a2cb7.

I confirm that the bug is fixed on my phone :) yay!

Unfortunately, I'm still looking for the flag to build the PRO version. I tried with `-DBUILD_PRO=TRUE` but it didn't work :thinking:

**Comment by chexmo** [comment] 2020-05-29 04:52
this still happens (using a moto e5)

**Comment by nesbox** [comment] 2020-05-29 06:16
@chexmo The issue is fixed on 0.80 version, what version do you use?
