### ISSUE TITLE
Please add an option in the config to disable the built-in TIC-80 keyboard.

### ISSUE THREAD

**Issue by StinkerB06** [nesbox/TIC-80#945] opened 2019-10-12 19:53 UTC
Some users on Android are complaining about the built-in virtual keyboard in TIC-80. They think it's uncomfortable to work with and would want to use their native Android keyboard instead.

Maybe have an option in the config for turning this off by default:
`OWNTOUCHKEYBOARD=false`

**Comment by Masternama-8000** [comment] 2019-10-13 13:33
@StinkerB06 This windows PC is not work :(

![notwork](https://user-images.githubusercontent.com/54476488/66716502-fed54d00-edeb-11e9-8bf4-d69dc8cfbb90.png)

`OWNTOUCHKEYBOARD=true`

**Comment by Masternama-8000** [comment] 2019-10-13 13:35
![screen](https://user-images.githubusercontent.com/54476488/66716532-5bd10300-edec-11e9-9b24-2b5889fc6c7a.gif)

**Comment by Masternama-8000** [comment] 2019-10-13 13:37
I found this problem
https://github.com/nesbox/TIC-80/issues/944

**Comment by nesbox** [comment] 2019-10-18 07:58
close as a duplicate of #785

**Closed by nesbox** 2019-10-18 07:58 UTC
