### ISSUE TITLE
No longer works on winXP?

### ISSUE THREAD

**Issue by eglavas** [nesbox/TIC-80#752] opened 2018-10-03 13:16 UTC
Is windows xp no longer supported?

0.60.3 is the last version that works.

**Comment by StinkerB06** [comment] 2018-10-06 07:31
I hope NesBox did it because Microsoft discontinued XP ~4 years prior.

**Comment by nesbox** [comment] 2018-10-08 06:46
TIC supports XP, I think there is a problem with SDLGPU library which doesn't work without OpenGL drivers. Will try to fix this in .80

**Comment by wadetb** [comment] 2019-12-11 02:16
One thing I noticed is that `GetSystemTimePreciseAsFileTime` is used by the JavaScript runtime but is Win8+.

**Comment by nesbox** [comment] 2020-09-19 07:18
Closing as a duplicate of #743

**Closed by nesbox** 2020-09-19 07:18 UTC
Labels: bug
