### ISSUE TITLE
RetroArch and State Saving

### ISSUE THREAD

**Issue by Kikasuru** [nesbox/TIC-80#1261] opened 2020-12-01 18:29 UTC
Hello, currently, state saving with RetroArch is strange, relying on the `pmem()` function which is mean for saving data that stays outside of the game, like high scores and the such. (Seen [here](https://tic80.com/play?cart=893).)  Is there a way we could add a specific function like `pmem()` that is meant for utilizing save states in RetroArch or have a way to define specific variables for saving states?  Thank you for your time.

**Comment by Kikasuru** [comment] 2020-12-01 18:32
Same could go with the native cheats function, it'd be nice to have an equivalent for that too.

**Comment by RobLoach** [comment] 2020-12-02 15:00
States in TIC-80 would be tricky, since they would depend on saving the internal scripting language's memory. I was looking at how to serialize that data, but it got complicated very quickly.

`pmem()` gives you an integer array, which is helpful, but not quite that much memory. You can only store 255 values.

We might be able to leverage [`memset`](https://github.com/nesbox/TIC-80/wiki/memset) for cheats as an alternative.

**Comment by msx80** [comment] 2020-12-02 16:40
I don't think this relates to tic80 api. To save states, we should dump the content of the VM state and reload it (beside tic80 state, but that's easy). It needs to be implemented on a per-language basis. Perhaps it's doable since the vms shouldn't be holding on to stuff like open files or system handles etc. In lua it should be possible to serialize the global table or something like that.
definitely not easy tho.

**Comment by asiekierka** [comment] 2020-12-02 18:34
For Lua, you might want to try something like https://github.com/MovingBlocks/eris

**Comment by joshgoebel** [comment] 2021-11-05 05:07
Would we even want this feature if it only supported a SINGLE engine?  IE, if only cartridges written in Lua supported save state - but not those written in Wren or JS or Squirrel?  So you'd never know with a given cartridge if save state was going to work or not... or if we were going to support this would it need to be supported by ALL engines across the board?  That would make the complexity of this much, much harder I think.

**Comment by joshgoebel** [comment] 2021-11-05 05:13
Of course individual games could work around this by writing their code such that they are resumable SOLELY from the state of RAM alone... yes, this would mean you couldn't store HUGE irreproducible amounts of data inside the VMs, you'd instead have to rely on the actual "hardware" RAM of the TIC-80 itself...  

I'm a little interested in that problem if anyone thinks that would be a step forward.  It would be easy to support with all engines since it's trivial to dump the TIC-80's RAM... (and the key internal state also - though ignoring buttons immediately after restart could also be done manually)... so one would only have to have a function that saved the state to RAM periodically (or we could add a `beforeQuit` callback)... and then when someone opened a cartridge back up it would need to look for that savestate in RAM if found restore the VM state based on that.

**Comment by RobLoach** [comment] 2021-11-05 19:50
I think we can close this. You can test it out with the [Multiplayer with pmem test](https://tic80.com/play?cart=893)....

1. Download [thecart.tic](https://tic80.com/cart/6126f49d64a9848cd345e7b6f2b8e384/multiplayer_with_pmem.tic)
2. Launch in RetroArch by either Load Content, or `retroarch -L tic80_libretro.so cart.tic`
3. Move one of the players somewhere
4. Save a state
5. Close the game
6. Re-load the cart
7. Load the state, and see that it's moved.

While it doesn't capture the whole memory state, it does capture `pmem`. Not sure how we could accomplish it without the persistent memory.

As a developer, it requires capturing all persistent data in pmem, so it does need some work. Would like to see more availalbe pmem data.

**Closed** 2021-11-06 14:55 UTC
Labels: enhancement
