### ISSUE TITLE
Raspberry Pi low performance

### ISSUE THREAD

**Issue by nesbox** [nesbox/TIC-80#393] opened 2017-11-13 05:47 UTC

**Comment by jahodfra** [comment] 2017-11-14 21:08
https://imgur.com/gallery/fj319

Please see that just api_blit takes 20% time on Raspberry Pi. The rest seems to be caused by slower general performance.

**Comment by jahodfra** [comment] 2017-11-14 21:56
I checked the code and it seems there is extensive use of nibbles (half bytes). ARM processors are not fun of unaligned access - meaning access to addresses not divisible by 4. There is probably large performance penalty with that. https://www.heyrick.co.uk/armwiki/Unaligned_data_access

I am wondering if it is better to optimize setting lines of pixels (1). Where e.g. 8 consecutive aligned pixels (32bits) can be set by one instruction or by using memory with gaps (2) e.g. using int32 for each pixel.
This can be done even for copying sprites (if the sprite is not scaled or rotated).

Generally I believe that using (1) would mean lot of coding and possibly even change of api (otherwise e.g. rotated sprites would not benefit from that).

Solution (2) should be more straightforward, but I am not sure about outcomes.

**Comment by nesbox** [comment] 2017-11-15 06:46
@jahodfra thanks for the info, I'll try to do something
btw, what profiler did you use?

**Comment by jahodfra** [comment] 2017-11-15 08:28
I compiled the code with -pg flag and then used gprof with the following
script https://github.com/jrfonseca/gprof2dot

I still want to run the script on Rpi2, where I suppose the performance
issues were larger. (because it run multiple times slower). Btw. I think I
forgot to change the branch for Rpi3 so it maybe uses software renderer.

I am also considering just writing simple C program with limited number of
steps just to profile drawing functions. It is hard to use absolute times
in the profile output when the duration of run was different.

st 15. 11. 2017 v 7:46 odesílatel Vadim Grigoruk <notifications@github.com>
napsal:

**Comment by jahodfra** [comment] 2017-11-20 21:59
I think the majority performance bottleneck is using of nibbles, but that is strongly related to the memory model in TIC. I am not sure if this can be addressed without breaking memory layout. How important is cap of 80KB?

**Comment by nesbox** [comment] 2017-11-21 07:25
Of course, 80K is very important, but we could use some tricks and use the screen buffer without nibbles.
I'll try to create a test today...

**Comment by nesbox** [comment] 2017-11-21 08:05
@jahodfra Could you pls checkout to https://github.com/nesbox/TIC-80/tree/rpi_test and test on your RPi?
I removed nibbles using on the rendering stage
Thanks

**Comment by jahodfra** [comment] 2017-11-21 20:44
pi3 1208-1248
pi3-rpitest 996-1024 

pi2 4538-5126
pi2-rpitest 3715-3887

I compiled by make linux on pi3 (its faster there and I tried previous time to compile binary on pi2 and there was no difference in running time0.

for testing I use following script:
-- title:  Benchmark
-- author: frantisek
-- desc:   sprite performance tests
-- script: lua

local sprite_count = 1000
local max_steps = 120
local step = 0
local ctime = time()

function TIC()
    local a = step / 20
    local stime = time()
    cls(0)
    for x=0,sprite_count do 
        spr(1, 120+math.sin(x+a)*120, 68+math.cos(x-a)*68)
    end
    step = step + 1
    ctime = ctime + time() - stime
    if step == max_steps then
        trace(string.format("cummulative time %.3f", ctime))
        exit()
    end
end

**Comment by jahodfra** [comment] 2017-11-22 07:01
If I take the fastest time the improvement seems in range of 18% for both architectures. Pretty inconclusive (this can be related to removal of mapping function). For pi2 being playable we would need something like 75% improvement.

**Comment by jahodfra** [comment] 2017-11-26 21:36
I cherry-picked 87dcc0399ea90d46e81dfa197882d1f217c76271 above my pull request #414.
On Raspberry pi 3 I got 10% speed improvement on sprite function. Still on Raspberry 2 aprox. 40% time is spent in api_blit function. I suppose that's a tax for the simulation of CRT ray drawing.

I am wondering if I can bit speed that up. Still it's post-processing which needs memory to be copied twice.

**Comment by jahodfra** [comment] 2017-11-29 22:07
#425 #413 #423 These pull requests speed up the TIC-80. Even after merging over half of the time is spent in drawTile (when running 8bit panda) and the panda is too slow on RPI2.

**Comment by jahodfra** [comment] 2017-11-30 07:19
I am getting out of ideas how to speed up drawTile.
Possible options:

- try differently aligned memory for sprites and screen. (We suppose that reading a nibble is slower then reading a byte)
- fix size of for loops if the tile is not clipped. (It could allow better loop unrolling and compiler can use vector operations).
- try to speed up unclipped tile without tiling and rotation to see what maximum speed we can attain.

**Comment by nesbox** [comment] 2017-11-30 07:33
I'm still thinking that it's too early to optimize `drawTile()`, because I'm going to add some special rendering modes to TIC (like mode0 / mode1) and these optimisations can prevent me, let's wait a bit...

As for optimising performance for RPi2, you could remove all the clipping / nibbles at all, just to see it will help or not

**Comment by jahodfra** [comment] 2017-11-30 08:26
Can you please explain to me what is mode0, mode1? Something like XOR, OR, AND?
I think it make sense not to pay for what is not used. (so e.g. have fast paths and bit more complicated slower paths).

**Comment by nesbox** [comment] 2017-11-30 08:50
no, it's something other, it's like your video processor uses another mode

**Comment by jahodfra** [comment] 2017-11-30 10:56
So do you have any objections to #423 ? I haven't been able to google what you mean by video processing modes (maybe blending modes?). What property should I keep?

Regarding to support for RPI2 - I will try what is possible and I understand that not all changes should be merged back (for proper playing it would need twice the speed so probably it is not even reachable platform).

Btw, do you plan to somehow take advantage of multiple threads in drawing?

**Comment by nesbox** [comment] 2017-11-30 11:47
never mind about modes, I still don't know how it will work or even would it be 😄 

to be honest, I try to avoid multithreading, because it always generates a large number of bugs

**Comment by jahodfra** [comment] 2017-11-30 13:09
I can imagine 3 threads caring about different parts of screen splitting all drawing operations. That could speed up drawTile, but would kill the performance of setPixel, getPixel.

Just imagine that like software [Rube Goldberg machine](https://en.wikipedia.org/wiki/Rube_Goldberg_machine).

**Comment by jahodfra** [comment] 2017-12-03 10:51
I tested various methods. I wasn't able to squeeze more perf. from my Raspberry B+ (so I suppose we should mark the platform as not supported). On Rpi3 everything runs fine.

It is possible to divide drawTile into 16 cases. (8 orientations and 2 depending if the x position of the tile is aligned with the screen). That can improve performance of the function maximally about 18% probably half of it. So the performance of TIC about cca 7-8%. Unfortunately it is a lot of hard coding and it is not compatible with overlap drawing feature (that would mean 32 hand optimized cases).

Therefore I am not going to optimize the performance more.

**Comment by jahodfra** [comment] 2017-12-03 12:33
My exploratory code is in jahodfra/TIC-80@2e8929f0604c056c6d11061c2f15fadd89270d82

**Comment by jahodfra** [comment] 2017-12-09 11:30
Therefore I recommend to only support Rpi3.
I run https://tic.computer/play?cart=153 on version before optimization and the current version.

Test | Old 90259da4c1a7da43e3a3868c5b73e5d5ebc75b73 | Current 86a320e9ad7e52869fd07b50b3b1b7607d2bf2f9
------|-----------|--------------
Shape | 1150 | 975
Map | 10 | 18
Sprites | 1800 | 29000
Particles | 2800 | 3000
Write Screen | 90 | 90
Read & Write Screen|  26 | 25
Math.Random | 10 000 | 10 000
Math.SquareRoot | 94 | 88
Math.SinCos | 105 | 105

The 8.bit panda https://tic.computer/play?cart=188 seems to me bit snappier now. But it was playable even before. I would recommend to keep that performance. I am not sure if decrease in Shape test speed is important to fix.

**Comment by nesbox** [comment] 2017-12-09 14:48
Nice job! @jahodfra 👍

**Comment by technomancy** [comment] 2018-01-21 20:36
The `drawtile4` branch improves performance greatly on my pi3 (bringing it from 0.2 fps on master to ~1 fps) I'm curious as to whether this is roughly the expected performance or if there might be more I could do to improve it?

**Comment by jahodfra** [comment] 2018-01-21 21:05
That branch is quite old and doesn't implement OVR function (overdraw writing mode).
I am sure that I haven't seen 5 times speedup otherwise I would go for it.

Can you share your test?

**Comment by technomancy** [comment] 2018-01-21 21:43
I'm afraid I don't have anything scientific, just "launch TIC-80, wait for the prompt, type a key, count how many seconds it takes before the output shows up". I haven't even tried any games, just the initial console thing.

**Comment by jahodfra** [comment] 2018-01-21 21:57
@technomancy Can you please try performance in this cartridge https://tic.computer/play?cart=153
Just run sprites test and mark numbers for both configurations.

Thanks.

**Comment by jahodfra** [comment] 2018-01-24 22:14
I measured increase from 2900 to 3800 (24% in fullscreen on Rpi3 on raspbian). I think that's a maximum possible speedup. "drawtile4" is old branch and is not correct (it just implements speed up on very specific conditions). I am not sure if it is worthy to invest lot of time (and bloat a code) to get e.g. 15% speedup. I also suppose that with the current setup your TIC don't run 1 fps.

**Comment by hseiken** [comment] 2018-01-24 23:05
Does TiC upscale after it draws the screen or does it treat pixels as boxes and scales the 'snap' of them?  Would going from one to the other have any impact whatsoever?

**Comment by jahodfra** [comment] 2018-01-26 16:18
Please don't speculate, rather measure on the current head.

**Comment by technomancy** [comment] 2018-01-26 17:09
> I also suppose that with the current setup your TIC don't run 1 fps.

What do you mean by this? It's currently running at 0.2 fps when I run it built from master, and I'm trying to determine what the expected performance is. Can you think of any factors that might cause a slowdown like this? (Missing GPU drivers, outdated SDL version, etc)

**Comment by jahodfra** [comment] 2018-01-26 17:38
@technomancy Please follow this article http://www.raspberryconnect.com/gamessoftware/item/314-trying_out_opengl_on_raspberry_pi_3

With OpenGL drivers the performance is fine, but they are not enabled by default.

**Comment by technomancy** [comment] 2018-01-27 17:21
@jahodfra That's exactly what I needed; thanks. It runs perfectly smooth now. (I get basically the same numbers for most of the benchmarks other than "Write Screen" which jumped to 110, but the performance is completely different.)

I'll add a note to the wiki since it doesn't seem to mention this at all.

**Comment by carlsmith** [comment] 2018-09-05 00:05
One other thing: The build instructions only mention installing `liblua5.3-dev` (obviously for Lua), and don't seem to cover other languages. I'm using JS and am interested in Wren.

**Comment by greywire** [comment] 2018-09-07 20:56
How DO you get this working on newest versions of raspberry pi?

**Closed** 2020-10-28 14:45 UTC
