### ISSUE TITLE
Streaming TIC-80 via Discord causes some weird screen glitching

### ISSUE THREAD

**Issue by NARbluebear** [nesbox/TIC-80#2440] opened 2024-01-18 05:33 UTC
While streaming, the screen kinda flickers (with two additional views in the leftmost corners). The middle and bottom-left views are frozen, too. The flickering stops when you stop streaming. Vsync doesn't seem to change a thing about this, either. Everyone else in the voice chat can see this as well. ![image](https://github.com/nesbox/TIC-80/assets/31386797/653b8fa2-0c6b-44c5-bc44-ef2e8b675307)
Specs:
CPU: AMD Ryzen 5 5500
GPU: Radeon RX 460
Motherboard: GIGABYTE B450M DS3H WIFI
RAM: 2x TeamGroup Elite 16GB DDR4 3200
PSU: Thermaltake SMART BM2 650W

**Comment by TimotheeGreg** [comment] 2024-01-18 16:22
It's related to #1914

**Comment by nesbox** [comment] 2024-01-20 15:58
yes, I think it's a duplicate of #1914

**Closed by nesbox** 2024-01-20 15:58 UTC
