### ISSUE TITLE
Web version locks up on Python syntax errors

### ISSUE THREAD

**Issue by nsxdavid** [nesbox/TIC-80#2297] opened 2023-09-07 15:24 UTC
When coding in Python, any syntax error will lock up on run.

For example, this line:

if btn(0) == 1: x+=1

On the exe version, will result in a proper error:
>run
>error while running TIC

>Traceback (most recent call last):
  File "<c-bound>", line 22
    if btn(0) == 1: x+=4
TypeError: expected 'bool', but got 
'int'

But when running on the Web version (on the create page), this will simply lock up the app and the page has to be refreshed to start using it again.

Version: 1.1.2736

**Comment by sogaiu** [comment] 2023-09-10 12:34
That happens for me too at https://tic80.com/create.

It doesn't necessarily lock up for other languages.  I only tested janet and lua though.

**Comment by blueloveTH** [comment] 2023-09-28 06:21
I can reproduce. Will look at it.

**Comment by blueloveTH** [comment] 2023-09-28 14:00
After some investigation, I've found the reason of this locking up.

![image](https://github.com/nesbox/TIC-80/assets/28104173/91944e96-9b1b-4b66-8f42-b52b86c44e54)

pocketpy needs c++ exceptions to be enabled to handle errors. According to [emscripten's docs](https://emscripten.org/docs/porting/exceptions.html):
> First, you can enable exceptions via Emscripten’s JavaScript-based support. To enable it, pass -fexceptions at both compile time and link time.

Although pocketpy itself always use `-fexceptions` flag, it is missing when linking with tic80's executable. So the exceptions won't be enabled in web platform.

## The Solution

In CMakeLists.txt, add `-fexceptions` as a linker flags to the executable.

![image](https://github.com/nesbox/TIC-80/assets/28104173/e20509e3-1f1e-41b5-8081-06f437da3a04)

**Comment by nesbox** [comment] 2023-10-08 12:25
fixed with #2315

**Closed by nesbox** 2023-10-08 12:25 UTC
