### ISSUE TITLE
Add an EDIT command

### ISSUE THREAD

**Issue by noxarivis** [nesbox/TIC-80#361] opened 2017-10-28 22:41 UTC
Adding an edit command to start the codeeditor is what i miss somehow

**Comment by nesbox** [comment] 2017-11-02 10:40
duplicate of #375

**Closed by nesbox** 2017-11-02 10:40 UTC
Labels: enhancement

**Comment by noxarivis** [comment] 2017-11-02 11:24
lol?    #375 is a duplicate of miner???

**Comment by nesbox** [comment] 2017-11-02 11:30
yes :) sorry
