### ISSUE TITLE
Please improve the JavaScript implementation.

### ISSUE THREAD

**Issue by LuisCebNu** [nesbox/TIC-80#1954] opened 2022-06-12 03:56 UTC
Is slow and very outdated compared to others (even Ruby).

**Comment by joshgoebel** [comment] 2022-06-12 04:21
Closing as a duplicate of #1191.   

From my own personal experience adding a new language runtime (WASM) I would imagine that this will require rather a large amount of effort - as well as care to ensure backwards compatibility with older cartridges (something quite important to us).   

If you might be willing to work on a PR for this yourself, that'd be awesome.  Otherwise (for now) you might be better to stick with one of the other runtimes. Personally I think Wren is a great substitute for JS with a very familiar syntax.

**Closed by joshgoebel** 2022-06-12 04:21 UTC
