### ISSUE TITLE
Removable Request (4 carts)

### ISSUE THREAD

**Issue by BuoYancYdabl** [nesbox/TIC-80#1983] opened 2022-07-17 17:09 UTC
Please, delete my old carts. They currently serving as placeholder, but I dont need that much placeholders and I dont want to flood the TIC80 with empty cartridges. If you need autentify is that actually me - write down and we will think about something. For example I can update cart with specified text on it.

[placeholder](https://tic80.com/play?cart=2391)
[placeholder1](https://tic80.com/play?cart=768)
[placeholder2](https://tic80.com/play?cart=672)
[placeholder3](https://tic80.com/play?cart=671)

If its impossible to delete carts - try opening links as "empty" so it can be rewriten later

**Comment by nesbox** [comment] 2022-07-20 08:01
We will add a delete button one day
duplicate of #1945

**Closed by nesbox** 2022-07-20 08:01 UTC
