### ISSUE TITLE
The new "Eval" command crashes TIC-80

### ISSUE THREAD

**Issue by GameExpress** [nesbox/TIC-80#681] opened 2018-08-15 14:25 UTC
The new version of TIC-80, version 0.70.1, added a new command called Eval.
Every time I use this command the program crashes.
This happens consitantly with every cartrige I tried.
I'm on Windows 10

**Comment by GrahamClemo** [comment] 2018-08-21 04:40
probably a duplicate of #653

**Comment by nesbox** [comment] 2018-08-21 05:34
yes, it's a duplicate

**Closed by nesbox** 2018-08-21 05:34 UTC
