### ISSUE TITLE
Linux build speed issues

### ISSUE THREAD

**Issue by andreyorst** [nesbox/TIC-80#1944] opened 2022-05-31 05:50 UTC
I've downloaded the latest stable Linux build 1.0.2164 from the releases page, and calculated the delta time in the default cart:

``` lua
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua

pt=0

function TIC()
	dt=(time()-pt)/1000
	pt=time()
	cls(13)
	print(dt,0,0)
end
```

In the latest build, it shows the value of approx `0.001`, which makes all games that use this value run much slower, compared to the web build and windows build, in which the delta time in this script is approx `0.01`. I've also downloaded the [0.90.1723](https://github.com/nesbox/TIC-80/releases/tag/v0.90.1723) build, and on the same machine, it shows the same delta time as a current web and win builds. Seems like the current Linux build doesn't really call `TIC` 60 times a second but a lot more than that?

Here's the result of running the same code in the web version, 0.90.1723 and 1.0.2164:
![image](https://user-images.githubusercontent.com/19470159/171101660-1fa672b0-5d7d-41e8-a270-fa22a59d2b99.png)

**Comment by nesbox** [comment] 2022-05-31 15:24
I think this is a duplicate of #1904

**Closed by nesbox** 2022-05-31 15:24 UTC
