### ISSUE TITLE
0.70.1 pro on Android: back button broken

### ISSUE THREAD

**Issue by BraininaBowl** [nesbox/TIC-80#668] opened 2018-08-13 14:04 UTC
Since the 0.70.1 update, tic-80 no longer reacts to the back button on my Android 8.1.0 OnePlus 6.

**Comment by fadookie** [comment] 2019-01-31 05:08
For me the back button seems to work to exit from a demo cart or the default hello world, but if I create a new cart and run it I get stuck in run mode forever and the back button doesn't work.

**Comment by fadookie** [comment] 2019-01-31 05:09
Possible dupe of https://github.com/nesbox/TIC-80/issues/717

**Comment by nesbox** [comment] 2019-12-12 09:26
fixed with the PR #975

**Closed by nesbox** 2019-12-12 09:26 UTC
Labels: bug
