### ISSUE TITLE
AltGr acts as Left Alt when pressed

### ISSUE THREAD

**Issue by SoundsDotZip** [nesbox/TIC-80#2282] opened 2023-08-25 23:02 UTC
I use a non-English keyboard layout (Hungarian) and for me the square brackets [ ] and curly brackets { } are a combination of AltGr and some other letter (F, G, B and N in the same order).
These combinations worked perfectly fine in 1.0, but in 1.1 AltGr act as left Alt instead.
For example, in 1.0 `AltGr + 1` was `~` and `AltGr + 3` was `^`, but in 1.1 they act as Alt+1 and Alt+3 which changes which editor I'm currently in.
This only seems to occur when the combinations are pressed.
When held down, the first frame is the incorrect one, but then the repeated presses are the correct AltGr Combinations.
This makes writing code super annoying, and I'm unable to use 1.1 until this is fixed.

**Comment by TimotheeGreg** [comment] 2023-08-26 06:16
That's a duplicate of #2265 which is already fixed for the coming hotfix release.

**Closed** 2023-08-26 07:06 UTC
