### ISSUE TITLE
Mouse wheel left or right scrolls down

### ISSUE THREAD

**Issue by gardrek** [nesbox/TIC-80#217] opened 2017-07-05 23:24 UTC
It seems the mouse wheel "tilt" left or right is mapped to "scroll down." When using the touchpad of my laptop to scroll up, it is difficult because any movement left or right causes it to scroll down.

Only tested on Linux.

**Comment by nesbox** [comment] 2020-10-28 14:02
Can't reproduce on the latest version.
Closing...

**Closed by nesbox** 2020-10-28 14:02 UTC
Labels: bug, input: mouse, platform: linux
