### ISSUE TITLE
All TIC-80 games run very slowly on Manjaro Linux

### ISSUE THREAD

**Issue by Timofei302** [nesbox/TIC-80#2041] opened 2022-12-01 15:11 UTC
I installed TIC-80 on my laptop, downloaded the ROM of the games. I started the game, but it works very slowly. I tried to run another game - the result is the same.
Then I tried to launch different releases - the result is the same. 
But at the same time, everything works fine in the browser and on the phone.

On phone:

https://user-images.githubusercontent.com/59145732/205086144-86f7257d-608e-42c2-b1aa-b641e617aef7.mp4

On notebook:

https://user-images.githubusercontent.com/59145732/205088366-fa518b4a-f9d7-4a4d-b7bf-e30af5478edc.mp4

OS: Manjaro Linux
DE: KDE Plasma 2.26.3
Kernel: 5.15.78-1-MANJARO (64 Bit)
CPU: AMD Ryzen 5 5500U
GPU: Integrated into the CPU
RAM: 15gb

**Comment by Timofei302** [comment] 2022-12-01 17:30
Tested on versions:
> Flatpak
> AUR (tic-80-git) [pro]
> Compiled version from GitHub
> Compiled version from GitHub Actions

**Comment by MineRobber9000** [comment] 2022-12-02 07:16
K2MU makes heavy use of `time()`, a function known to be broken in 1.0.x on non-Windows devices (#1904). However, it was believed that the Android build also suffered from this issue, which doesn't explain the game working well on Android.

I made a PR to fix the problem, but it was deemed an "incorrect" solution, and I have not gotten around to doing it "correctly" due to extreme crunch at the end of this semester of college for me. I will try and fix that soon (which ought to fix at least some of the issues with K2MU). Could you try some games that don't make as heavy use of `time()`? Something like [Soda Explorer](https://tic80.com/play?cart=3062) that doesn't rely on a correct `time()` implementation would give a better picture of the performance discrepancy (if one exists).

**Comment by Timofei302** [comment] 2022-12-02 08:35
I'll check it out when I get home. But I can say something else.

The Pirate Survival game works generally well, but it freezes the controls (except walking) and attack animations.

Everything is fine on the phone and in the browser.

**Comment by Timofei302** [comment] 2022-12-02 17:02
@MineRobber9000 but there are no problems with Soda Dungeon. Most likely the problem, as you said, is with the time() function.

Mobile:

https://user-images.githubusercontent.com/59145732/205345273-0e8a3145-88ed-4224-885d-6558bf84f0df.mp4

Notebook:

https://user-images.githubusercontent.com/59145732/205345700-70f9af08-6471-4262-8751-4dfe92a90014.mp4

**Comment by MineRobber9000** [comment] 2022-12-02 21:08
You'll never believe what function is being used in Pirate: Survival...

![image](https://user-images.githubusercontent.com/12676241/205386274-6ec691d2-0733-4bbd-a09b-35bf8876db1b.png)

Requesting this be closed as a dupe of #1904.

**Comment by joshgoebel** [comment] 2022-12-05 00:48
Closing per request as dup of time() issue.

**Closed by joshgoebel** 2022-12-05 00:48 UTC
Labels: platform: linux
