### ISSUE TITLE
Floating point string representation in fennel with non english locale

### ISSUE THREAD

**Issue by adrian-castravete** [nesbox/TIC-80#1270] opened 2020-12-10 16:40 UTC
I'll start off by specifying some things that are more than likely relevant.
I'm on linux and my locale settings are the following:
```
$ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=ro_RO.UTF-8
LC_TIME=ro_RO.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=ro_RO.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=ro_RO.UTF-8
LC_NAME=ro_RO.UTF-8
LC_ADDRESS=ro_RO.UTF-8
LC_TELEPHONE=ro_RO.UTF-8
LC_MEASUREMENT=ro_RO.UTF-8
LC_IDENTIFICATION=ro_RO.UTF-8
LC_ALL=
```

I said this as there's something specific to the numeric representation of real (floating point) numbers. In most cases we all agree that this is a floating point number: `1.234` for the result of 1234 / 1000. The Romanian locale is `1,234` however.

Now i have these two programs that are identical, save for the fact that they're different languages:
```lua
-- title:  game title
-- author: game developer
-- desc:   short description
-- script: lua

function threadFunc(start)
 local test = start
 while test > 0 do
  print(test)
  test = test - coroutine.yield()
 end
end

local thread = coroutine.create(threadFunc)

coroutine.resume(thread, 1 + math.random())

function TIC()
 cls()
 if not coroutine.resume(thread, 0.01) then
  print("Coroutine ended")
 end
end
```
and
```scheme
;; title:  game title
;; author: game developer
;; desc:   short description
;; script: fennel

(fn thread-func [start]
 (var test start)
 (while (> test 0)
  (print test)
  (set test (- test (coroutine.yield)))))

(var thread (coroutine.create thread-func))

(coroutine.resume thread (+ 1 (math.random)))

(global TIC
 (fn tic []
  (cls)
  (when 
   (not (coroutine.resume thread 0.01))
   (print "Coroutine ended"))))
```

The problem is that the `fennel` one just seems to hang whereas the `lua` one continues normally.
So here's the **lua**:
![Lua version](https://i.imgur.com/6IMCYKu.gif)
And here's the **fennel**:
![Fennel version](https://i.imgur.com/2Y8Vphz.gif)

Now the **representation** tipped me off to try and stringify the number I give to `resume`. So I changed that line to the following:
```
   (not (coroutine.resume thread "0.01"))
```
and it now more normally does something correctly:
![Fennel Stringify version](https://i.imgur.com/cxOQ5DM.gif)

But I wonder... _Is that normal?_

I mean... normal `fennel` doesn't behave that way...
```bash
$ fennel
Welcome to Fennel 0.6.0 on Lua 5.3!
Use (doc something) to view documentation.
Try installing readline via luarocks for a better repl experience.
>> (fn thread-func [start]
..(var test start)
..(while (> test 0)
..(print test)
..(set test (- test (coroutine.yield)))))
#<function: 0x563cf9eac4e0>
>> (var thread (coroutine.create thread-func))

>> (coroutine.resume thread (+ 1 (math.random)))
1.8401877167635
true
>> (coroutine.resume thread 0.01)
1.8301877167635
true
>> (coroutine.resume thread 0.01)
1.8201877167635
true
>> (coroutine.resume thread 0.5)
1.3201877167635
true
>> (coroutine.resume thread 1)
0.32018771676347
true
>> (coroutine.resume thread 0.1)
0.22018771676347
true
>> (coroutine.resume thread 0.1)
0.12018771676347
true
>> (coroutine.resume thread 0.1)
0.020187716763467
true
>> (coroutine.resume thread 0.1)
true
>> (coroutine.resume thread 0.1)
false	"cannot resume dead coroutine"
>> 
```

**Comment by nesbox** [comment] 2020-12-11 07:44
It's not normal, @technomancy could you pls look at it.
Thanks.

**Comment by technomancy** [comment] 2020-12-11 16:53
I'm having trouble reproducing this problem. I've generated the locales in question and exported environment variables such that `locale` produces the same output as what you've pasted above. I don't know much about locales so maybe there's something more I need to do? Is there more to it beyond editing `/etc/locale.gen`, running `locale-gen`, and setting the environment variables?

**Comment by adrian-castravete** [comment] 2020-12-11 21:34
I'm kind of puzzled myself. Do you, however, get the weird comma floating point representation?

**Comment by technomancy** [comment] 2020-12-12 01:05
I do not get the comma representation in TIC, however I did find that by calling `os.setlocale` I can reproduce the problem in Fennel on its own outside TIC.

It happens because Fennel parses the code an has to emit code back out again to be parsed by Lua. The "%.17g" format specifier is locale-aware and thus uses commas. The only non-locale-aware equivalent is "%q" which is guaranteed to be supported by the Lua parser; unfortunately on Lua 5.3 emits the value as hexadecimal, leading to less-readable compiler output.

We will come up with a fix for this in Fennel, but it's an odd one to be sure! Doesn't seem like there's any one clear solution.

**Comment by technomancy** [comment] 2020-12-12 17:54
Tracking this in our issue tracker here: https://todo.sr.ht/~technomancy/fennel/32

**Comment by adrian-castravete** [comment] 2020-12-12 20:57
Thank you very much for the explanations. Not a big problem. I'm just going to watch out for this one, so I don't get bitten in the future. :D

**Comment by joshgoebel** [comment] 2022-02-23 20:37
Closing per technomancy in his comment on #1336: 

> It includes a fix for https://github.com/nesbox/TIC-80/issues/1270

**Closed by joshgoebel** 2022-02-23 20:37 UTC
